// Corrida Quanta — bancos de perguntas de Química e Física (dados; a lógica fica em js/modes.js).
// Notação rica: _x / _{xy} = índice, ^x / ^{xy} = expoente (H_2O, C_6H_{12}O_6, m·v^2/2).
// elements:  { name, symbol, z, mass, tier: facil|medio|dificil, traps: [3 símbolos errados], why }
// molecules: { name, formula, cls: acido|base|sal|oxido|organico|simples|outro, tier, traps: [3 fórmulas erradas], why }
// physics:   { name, lhs, rhs, tier: 1..4, traps: [3 equações erradas], why, unit, unit_traps: [3 unidades erradas] }
// bio, geo:  { title, text, ans, traps: [3 respostas erradas], why, tier: 1..4 }
// "why" é a frase mostrada depois do erro. Revisão: Samuel (professor).
(() => {
  'use strict';
  window.QC = window.QC || {};
  QC.Banks = {
  elements: [
    {"name": "Hidrogênio", "symbol": "H", "z": 1, "mass": 1, "tier": "facil", "traps": ["Hi", "Hd", "Hg"], "why": "Hidrogênio é H, o mais leve de todos, número atômico 1."},
    {"name": "Hélio", "symbol": "He", "z": 2, "mass": 4, "tier": "facil", "traps": ["H", "Hl", "Hi"], "why": "Hélio é He: duas letras, gás nobre mais leve."},
    {"name": "Lítio", "symbol": "Li", "z": 3, "mass": 7, "tier": "facil", "traps": ["L", "Lt", "Lu"], "why": "Lítio é Li, o metal mais leve que existe."},
    {"name": "Berílio", "symbol": "Be", "z": 4, "mass": 9, "tier": "facil", "traps": ["B", "Br", "Bl"], "why": "Berílio é Be; B sozinho é o boro."},
    {"name": "Boro", "symbol": "B", "z": 5, "mass": 11, "tier": "facil", "traps": ["Bo", "Br", "Bh"], "why": "Boro é só B, uma letra, número atômico 5."},
    {"name": "Carbono", "symbol": "C", "z": 6, "mass": 12, "tier": "facil", "traps": ["Ca", "Cb", "Co"], "why": "Carbono é só C; Ca é cálcio e Co é cobalto."},
    {"name": "Nitrogênio", "symbol": "N", "z": 7, "mass": 14, "tier": "facil", "traps": ["Ni", "Nt", "Na"], "why": "Nitrogênio é só N; Na é sódio e Ni é níquel."},
    {"name": "Oxigênio", "symbol": "O", "z": 8, "mass": 16, "tier": "facil", "traps": ["Ox", "Os", "Og"], "why": "Oxigênio é só O, o elemento mais abundante na crosta."},
    {"name": "Flúor", "symbol": "F", "z": 9, "mass": 19, "tier": "facil", "traps": ["Fl", "Fe", "Fu"], "why": "Flúor é só F; Fe é ferro e Fl é fleróvio."},
    {"name": "Neônio", "symbol": "Ne", "z": 10, "mass": 20, "tier": "facil", "traps": ["N", "No", "Nn"], "why": "Neônio é Ne, gás nobre das luzes de letreiro."},
    {"name": "Sódio", "symbol": "Na", "z": 11, "mass": 23, "tier": "facil", "traps": ["So", "S", "Sd"], "why": "Sódio é Na, do latim natrium."},
    {"name": "Magnésio", "symbol": "Mg", "z": 12, "mass": 24, "tier": "facil", "traps": ["Ma", "Mn", "M"], "why": "Magnésio é Mg; Mn é manganês."},
    {"name": "Alumínio", "symbol": "Al", "z": 13, "mass": 27, "tier": "facil", "traps": ["A", "Am", "Au"], "why": "Alumínio é Al; Au é ouro, Am é amerício."},
    {"name": "Silício", "symbol": "Si", "z": 14, "mass": 28, "tier": "facil", "traps": ["S", "Sl", "Sc"], "why": "Silício é Si; S sozinho é enxofre."},
    {"name": "Fósforo", "symbol": "P", "z": 15, "mass": 31, "tier": "facil", "traps": ["F", "Fo", "Ph"], "why": "Fósforo é P, de phosphorus; F é flúor."},
    {"name": "Enxofre", "symbol": "S", "z": 16, "mass": 32, "tier": "facil", "traps": ["En", "Ex", "Su"], "why": "Enxofre é S, de sulphur em latim."},
    {"name": "Cloro", "symbol": "Cl", "z": 17, "mass": 35.5, "tier": "facil", "traps": ["C", "Co", "Cr"], "why": "Cloro é Cl; Co é cobalto e Cr é cromo."},
    {"name": "Argônio", "symbol": "Ar", "z": 18, "mass": 40, "tier": "facil", "traps": ["A", "Ag", "An"], "why": "Argônio é Ar, gás nobre; Ag é prata."},
    {"name": "Cálcio", "symbol": "Ca", "z": 20, "mass": 40, "tier": "facil", "traps": ["C", "Cl", "Cc"], "why": "Cálcio é Ca; C sozinho é carbono."},
    {"name": "Ferro", "symbol": "Fe", "z": 26, "mass": 56, "tier": "facil", "traps": ["F", "Fr", "Ir"], "why": "Ferro é Fe, do latim ferrum; F é flúor."},
    {"name": "Zinco", "symbol": "Zn", "z": 30, "mass": 65, "tier": "facil", "traps": ["Z", "Zi", "Zc"], "why": "Zinco é Zn, número atômico 30."},
    {"name": "Iodo", "symbol": "I", "z": 53, "mass": 127, "tier": "facil", "traps": ["Io", "Id", "In"], "why": "Iodo é só I; In é índio."},
    {"name": "Potássio", "symbol": "K", "z": 19, "mass": 39, "tier": "medio", "traps": ["P", "Po", "Pt"], "why": "Potássio é K, do latim kalium."},
    {"name": "Cobre", "symbol": "Cu", "z": 29, "mass": 63.5, "tier": "medio", "traps": ["Co", "Cb", "Cr"], "why": "Cobre é Cu, do latim cuprum; Co é cobalto."},
    {"name": "Prata", "symbol": "Ag", "z": 47, "mass": 108, "tier": "medio", "traps": ["Pr", "Pt", "Pa"], "why": "Prata é Ag, do latim argentum."},
    {"name": "Ouro", "symbol": "Au", "z": 79, "mass": 197, "tier": "medio", "traps": ["O", "Ou", "Ag"], "why": "Ouro é Au, do latim aurum; Ag é prata."},
    {"name": "Chumbo", "symbol": "Pb", "z": 82, "mass": 207, "tier": "medio", "traps": ["Ch", "Cb", "Cu"], "why": "Chumbo é Pb, do latim plumbum."},
    {"name": "Mercúrio", "symbol": "Hg", "z": 80, "mass": 201, "tier": "medio", "traps": ["Me", "Mc", "Mr"], "why": "Mercúrio é Hg, de hydrargyrum, 'prata líquida'."},
    {"name": "Estanho", "symbol": "Sn", "z": 50, "mass": 119, "tier": "medio", "traps": ["Es", "Et", "St"], "why": "Estanho é Sn, do latim stannum."},
    {"name": "Manganês", "symbol": "Mn", "z": 25, "mass": 55, "tier": "medio", "traps": ["Mg", "Ma", "Mm"], "why": "Manganês é Mn; Mg é magnésio."},
    {"name": "Níquel", "symbol": "Ni", "z": 28, "mass": 59, "tier": "medio", "traps": ["N", "Nq", "Nk"], "why": "Níquel é Ni; N sozinho é nitrogênio."},
    {"name": "Cobalto", "symbol": "Co", "z": 27, "mass": 59, "tier": "medio", "traps": ["Cb", "Cu", "Ct"], "why": "Cobalto é Co; Cu é cobre."},
    {"name": "Cromo", "symbol": "Cr", "z": 24, "mass": 52, "tier": "medio", "traps": ["Cm", "Co", "Ch"], "why": "Cromo é Cr; Cm é cúrio."},
    {"name": "Bromo", "symbol": "Br", "z": 35, "mass": 80, "tier": "medio", "traps": ["B", "Bo", "Bm"], "why": "Bromo é Br, único não metal líquido; B é boro."},
    {"name": "Bário", "symbol": "Ba", "z": 56, "mass": 137, "tier": "medio", "traps": ["B", "Br", "Bi"], "why": "Bário é Ba; Bi é bismuto."},
    {"name": "Urânio", "symbol": "U", "z": 92, "mass": 238, "tier": "medio", "traps": ["Ur", "Un", "Ua"], "why": "Urânio é só U, número atômico 92."},
    {"name": "Platina", "symbol": "Pt", "z": 78, "mass": 195, "tier": "medio", "traps": ["Pl", "Pa", "P"], "why": "Platina é Pt; P é fósforo, Pa é protactínio."},
    {"name": "Tungstênio", "symbol": "W", "z": 74, "mass": 184, "tier": "medio", "traps": ["Tu", "Tg", "Tn"], "why": "Tungstênio é W, de wolfrâmio, o nome alemão."},
    {"name": "Antimônio", "symbol": "Sb", "z": 51, "mass": 122, "tier": "medio", "traps": ["An", "At", "Am"], "why": "Antimônio é Sb, do latim stibium."},
    {"name": "Titânio", "symbol": "Ti", "z": 22, "mass": 48, "tier": "medio", "traps": ["T", "Tt", "Tn"], "why": "Titânio é Ti, número atômico 22."},
    {"name": "Criptônio", "symbol": "Kr", "z": 36, "mass": 84, "tier": "medio", "traps": ["Cr", "Cp", "K"], "why": "Criptônio é Kr; Cr é cromo, K é potássio."},
    {"name": "Xenônio", "symbol": "Xe", "z": 54, "mass": 131, "tier": "medio", "traps": ["X", "Xn", "Xo"], "why": "Xenônio é Xe, gás nobre pesado, número 54."},
    {"name": "Radônio", "symbol": "Rn", "z": 86, "mass": 222, "tier": "medio", "traps": ["Ra", "Rd", "Ro"], "why": "Radônio é Rn; Ra é rádio."},
    {"name": "Estrôncio", "symbol": "Sr", "z": 38, "mass": 88, "tier": "medio", "traps": ["Es", "St", "Sn"], "why": "Estrôncio é Sr; Sn é estanho."},
    {"name": "Rubídio", "symbol": "Rb", "z": 37, "mass": 85, "tier": "dificil", "traps": ["Ru", "R", "Rd"], "why": "Rubídio é Rb; Ru é rutênio."},
    {"name": "Césio", "symbol": "Cs", "z": 55, "mass": 133, "tier": "dificil", "traps": ["Ce", "C", "Ci"], "why": "Césio é Cs; Ce é cério."},
    {"name": "Germânio", "symbol": "Ge", "z": 32, "mass": 73, "tier": "dificil", "traps": ["Gm", "Gr", "G"], "why": "Germânio é Ge, semicondutor, número atômico 32."},
    {"name": "Arsênio", "symbol": "As", "z": 33, "mass": 75, "tier": "dificil", "traps": ["Ar", "Ac", "A"], "why": "Arsênio é As; Ar é argônio."},
    {"name": "Selênio", "symbol": "Se", "z": 34, "mass": 79, "tier": "dificil", "traps": ["S", "Sl", "Si"], "why": "Selênio é Se; S é enxofre e Si é silício."},
    {"name": "Telúrio", "symbol": "Te", "z": 52, "mass": 128, "tier": "dificil", "traps": ["Tl", "Tu", "T"], "why": "Telúrio é Te; Tl é tálio."},
    {"name": "Bismuto", "symbol": "Bi", "z": 83, "mass": 209, "tier": "dificil", "traps": ["Bs", "B", "Bm"], "why": "Bismuto é Bi, número atômico 83."},
    {"name": "Polônio", "symbol": "Po", "z": 84, "mass": 209, "tier": "dificil", "traps": ["P", "Pl", "Pn"], "why": "Polônio é Po, descoberto por Marie Curie."},
    {"name": "Cádmio", "symbol": "Cd", "z": 48, "mass": 112, "tier": "dificil", "traps": ["Ca", "Cm", "Cc"], "why": "Cádmio é Cd; Ca é cálcio."},
    {"name": "Índio", "symbol": "In", "z": 49, "mass": 115, "tier": "dificil", "traps": ["I", "Id", "Ii"], "why": "Índio é In; I sozinho é iodo."},
    {"name": "Gálio", "symbol": "Ga", "z": 31, "mass": 70, "tier": "dificil", "traps": ["G", "Gl", "Ge"], "why": "Gálio é Ga, metal que derrete na mão; Ge é germânio."},
    {"name": "Escândio", "symbol": "Sc", "z": 21, "mass": 45, "tier": "dificil", "traps": ["Es", "Ec", "Si"], "why": "Escândio é Sc, de Escandinávia."},
    {"name": "Vanádio", "symbol": "V", "z": 23, "mass": 51, "tier": "dificil", "traps": ["Va", "Vn", "Vd"], "why": "Vanádio é só V, número atômico 23."},
    {"name": "Molibdênio", "symbol": "Mo", "z": 42, "mass": 96, "tier": "dificil", "traps": ["Mb", "Ml", "M"], "why": "Molibdênio é Mo, número atômico 42."},
    {"name": "Paládio", "symbol": "Pd", "z": 46, "mass": 106, "tier": "dificil", "traps": ["Pa", "Pl", "P"], "why": "Paládio é Pd; Pa é protactínio."},
    {"name": "Irídio", "symbol": "Ir", "z": 77, "mass": 192, "tier": "dificil", "traps": ["I", "Id", "In"], "why": "Irídio é Ir; I é iodo e In é índio."},
    {"name": "Ósmio", "symbol": "Os", "z": 76, "mass": 190, "tier": "dificil", "traps": ["O", "Om", "Oi"], "why": "Ósmio é Os, o metal mais denso."},
    {"name": "Tálio", "symbol": "Tl", "z": 81, "mass": 204, "tier": "dificil", "traps": ["Ta", "T", "Th"], "why": "Tálio é Tl; Ta é tântalo e Th é tório."},
    {"name": "Rádio", "symbol": "Ra", "z": 88, "mass": 226, "tier": "dificil", "traps": ["Rd", "R", "Rn"], "why": "Rádio é Ra; Rn é radônio."},
    {"name": "Tório", "symbol": "Th", "z": 90, "mass": 232, "tier": "dificil", "traps": ["To", "T", "Tr"], "why": "Tório é Th, de Thor, deus nórdico."}
  ],
  molecules: [
    {"name": "Água", "formula": "H_2O", "cls": "outro", "tier": "facil", "traps": ["H_2O_2", "HO_2", "H_3O"], "why": "Água: 2 hidrogênios e 1 oxigênio, H₂O."},
    {"name": "Gás carbônico", "formula": "CO_2", "cls": "oxido", "tier": "facil", "traps": ["CO", "C_2O", "CO_3"], "why": "Gás carbônico tem 2 oxigênios, CO₂; CO é o monóxido."},
    {"name": "Monóxido de carbono", "formula": "CO", "cls": "oxido", "tier": "facil", "traps": ["CO_2", "C_2O", "CO_3"], "why": "Monóxido = 1 oxigênio: CO, gás tóxico da combustão incompleta."},
    {"name": "Gás oxigênio", "formula": "O_2", "cls": "simples", "tier": "facil", "traps": ["O", "O_3", "H_2O"], "why": "Gás oxigênio é diatômico: O₂; O₃ é o ozônio."},
    {"name": "Ozônio", "formula": "O_3", "cls": "simples", "tier": "facil", "traps": ["O_2", "O", "O_4"], "why": "Ozônio tem 3 átomos de oxigênio: O₃."},
    {"name": "Gás hidrogênio", "formula": "H_2", "cls": "simples", "tier": "facil", "traps": ["H", "H_3", "H_2O"], "why": "Hidrogênio gasoso é diatômico: H₂."},
    {"name": "Gás nitrogênio", "formula": "N_2", "cls": "simples", "tier": "facil", "traps": ["N", "N_3", "NH_3"], "why": "Nitrogênio do ar é N₂, molécula diatômica com ligação tripla."},
    {"name": "Amônia", "formula": "NH_3", "cls": "outro", "tier": "facil", "traps": ["NH_4", "NH_2", "NH"], "why": "Amônia: 1 nitrogênio e 3 hidrogênios, NH₃; NH₄⁺ é o íon amônio."},
    {"name": "Metano", "formula": "CH_4", "cls": "organico", "tier": "facil", "traps": ["CH_3", "C_2H_6", "CH_2"], "why": "Metano é o alcano mais simples: 1 carbono e 4 hidrogênios, CH₄."},
    {"name": "Cloreto de sódio (sal de cozinha)", "formula": "NaCl", "cls": "sal", "tier": "facil", "traps": ["NaCl_2", "Na_2Cl", "NaClO"], "why": "Sal de cozinha: Na⁺ e Cl⁻ na proporção 1:1, NaCl."},
    {"name": "Água oxigenada", "formula": "H_2O_2", "cls": "outro", "tier": "facil", "traps": ["H_2O", "HO_2", "H_2O_3"], "why": "Água oxigenada tem um oxigênio a mais que a água: H₂O₂."},
    {"name": "Ácido clorídrico", "formula": "HCl", "cls": "acido", "tier": "facil", "traps": ["HCl_2", "H_2Cl", "HClO"], "why": "Ácido clorídrico: HCl, hidrogênio e cloro na proporção 1:1."},
    {"name": "Soda cáustica (hidróxido de sódio)", "formula": "NaOH", "cls": "base", "tier": "facil", "traps": ["Na(OH)_2", "Na_2OH", "NaO"], "why": "Hidróxido de sódio: Na⁺ e OH⁻, NaOH."},
    {"name": "Gás cloro", "formula": "Cl_2", "cls": "simples", "tier": "facil", "traps": ["Cl", "Cl_3", "HCl"], "why": "Cloro gasoso é diatômico: Cl₂."},
    {"name": "Cloreto de potássio", "formula": "KCl", "cls": "sal", "tier": "facil", "traps": ["KCl_2", "K_2Cl", "KClO_3"], "why": "Cloreto de potássio: K⁺ e Cl⁻ na proporção 1:1, KCl."},
    {"name": "Óxido de magnésio", "formula": "MgO", "cls": "oxido", "tier": "facil", "traps": ["MgO_2", "Mg_2O", "Mg(OH)_2"], "why": "Magnésio é +2 e oxigênio é −2: MgO."},
    {"name": "Cal virgem (óxido de cálcio)", "formula": "CaO", "cls": "oxido", "tier": "facil", "traps": ["CaO_2", "Ca_2O", "Ca(OH)_2"], "why": "Cal virgem é CaO; Ca(OH)₂ é a cal hidratada."},
    {"name": "Dióxido de enxofre", "formula": "SO_2", "cls": "oxido", "tier": "facil", "traps": ["SO_3", "SO", "S_2O"], "why": "Dióxido = 2 oxigênios: SO₂; SO₃ é o trióxido."},
    {"name": "Dióxido de nitrogênio", "formula": "NO_2", "cls": "oxido", "tier": "facil", "traps": ["NO", "N_2O", "NO_3"], "why": "Dióxido de nitrogênio: NO₂, gás castanho da poluição."},
    {"name": "Óxido nitroso (gás hilariante)", "formula": "N_2O", "cls": "oxido", "tier": "facil", "traps": ["NO", "NO_2", "N_2O_3"], "why": "Gás hilariante: 2 nitrogênios e 1 oxigênio, N₂O."},
    {"name": "Ácido sulfúrico", "formula": "H_2SO_4", "cls": "acido", "tier": "medio", "traps": ["H_2SO_3", "H_2S", "HSO_4"], "why": "Ácido sulfúrico tem 4 oxigênios; H₂SO₃ é o sulfuroso."},
    {"name": "Ácido nítrico", "formula": "HNO_3", "cls": "acido", "tier": "medio", "traps": ["HNO_2", "H_2NO_3", "HNO_4"], "why": "Ácido nítrico tem 3 oxigênios: HNO₃; HNO₂ é o nitroso."},
    {"name": "Ácido fosfórico", "formula": "H_3PO_4", "cls": "acido", "tier": "medio", "traps": ["H_2PO_4", "H_3PO_3", "HPO_4"], "why": "Ácido fosfórico tem 3 H e 4 O: H₃PO₄."},
    {"name": "Ácido carbônico", "formula": "H_2CO_3", "cls": "acido", "tier": "medio", "traps": ["HCO_3", "H_2CO_2", "H_2CO_4"], "why": "Ácido carbônico = CO₂ + H₂O: H₂CO₃."},
    {"name": "Carbonato de cálcio", "formula": "CaCO_3", "cls": "sal", "tier": "medio", "traps": ["CaCO_2", "Ca_2CO_3", "CaCO_4"], "why": "Carbonato é CO₃²⁻ e cálcio é +2: CaCO₃, o calcário."},
    {"name": "Bicarbonato de sódio", "formula": "NaHCO_3", "cls": "sal", "tier": "medio", "traps": ["Na_2CO_3", "NaCO_3", "NaHCO_2"], "why": "Bicarbonato tem H: NaHCO₃; carbonato de sódio é Na₂CO₃."},
    {"name": "Hidróxido de cálcio (cal hidratada)", "formula": "Ca(OH)_2", "cls": "base", "tier": "medio", "traps": ["CaOH", "Ca_2OH", "Ca(OH)_3"], "why": "Cálcio é +2, precisa de 2 OH⁻: Ca(OH)₂."},
    {"name": "Cloreto de cálcio", "formula": "CaCl_2", "cls": "sal", "tier": "medio", "traps": ["CaCl", "Ca_2Cl", "CaCl_3"], "why": "Cálcio +2 e cloro −1: CaCl₂."},
    {"name": "Sulfato de cobre II", "formula": "CuSO_4", "cls": "sal", "tier": "medio", "traps": ["CuSO_3", "Cu_2SO_4", "CuS"], "why": "Sulfato é SO₄²⁻ e cobre II é +2: CuSO₄, sal azul; Cu₂SO₄ seria o de cobre I."},
    {"name": "Óxido de ferro III (ferrugem)", "formula": "Fe_2O_3", "cls": "oxido", "tier": "medio", "traps": ["FeO", "Fe_3O_2", "FeO_3"], "why": "Ferro +3 e oxigênio −2 cruzam os índices: Fe₂O₃."},
    {"name": "Óxido de alumínio (alumina)", "formula": "Al_2O_3", "cls": "oxido", "tier": "medio", "traps": ["AlO", "Al_3O_2", "AlO_3"], "why": "Alumínio +3 e oxigênio −2: Al₂O₃."},
    {"name": "Hidróxido de potássio", "formula": "KOH", "cls": "base", "tier": "medio", "traps": ["K(OH)_2", "K_2OH", "KO"], "why": "Potássio é +1, um só OH⁻: KOH."},
    {"name": "Hidróxido de magnésio (leite de magnésia)", "formula": "Mg(OH)_2", "cls": "base", "tier": "medio", "traps": ["MgOH", "Mg_2OH", "Mg(OH)_3"], "why": "Magnésio +2 pede 2 OH⁻: Mg(OH)₂."},
    {"name": "Nitrato de sódio", "formula": "NaNO_3", "cls": "sal", "tier": "medio", "traps": ["NaNO_2", "Na_2NO_3", "NaNO_4"], "why": "Nitrato é NO₃⁻: NaNO₃; NaNO₂ é o nitrito."},
    {"name": "Nitrato de potássio (salitre)", "formula": "KNO_3", "cls": "sal", "tier": "medio", "traps": ["KNO_2", "K_2NO_3", "KNO_4"], "why": "Salitre: K⁺ e NO₃⁻, KNO₃."},
    {"name": "Carbonato de sódio (barrilha)", "formula": "Na_2CO_3", "cls": "sal", "tier": "medio", "traps": ["NaCO_3", "NaHCO_3", "Na_2CO_2"], "why": "Carbonato é CO₃²⁻, precisa de 2 Na⁺: Na₂CO₃."},
    {"name": "Sulfato de potássio", "formula": "K_2SO_4", "cls": "sal", "tier": "medio", "traps": ["KSO_4", "K_2SO_3", "K_2S"], "why": "Sulfato SO₄²⁻ com 2 K⁺: K₂SO₄."},
    {"name": "Ácido fluorídrico", "formula": "HF", "cls": "acido", "tier": "medio", "traps": ["HF_2", "H_2F", "HFO"], "why": "Ácido fluorídrico: HF, ataca até o vidro."},
    {"name": "Ácido bromídrico", "formula": "HBr", "cls": "acido", "tier": "medio", "traps": ["HBr_2", "H_2Br", "HBrO"], "why": "Ácido bromídrico: HBr, hidrácido como o HCl."},
    {"name": "Gás sulfídrico (ácido sulfídrico)", "formula": "H_2S", "cls": "acido", "tier": "medio", "traps": ["HS", "HS_2", "H_2SO_3"], "why": "Sulfídrico: enxofre −2 com 2 H, H₂S, cheiro de ovo podre."},
    {"name": "Trióxido de enxofre", "formula": "SO_3", "cls": "oxido", "tier": "medio", "traps": ["SO_2", "S_2O_3", "SO_4"], "why": "Trióxido = 3 oxigênios: SO₃; com água forma H₂SO₄."},
    {"name": "Dióxido de silício (sílica)", "formula": "SiO_2", "cls": "oxido", "tier": "medio", "traps": ["SiO", "Si_2O", "SiO_3"], "why": "Sílica, principal componente da areia: SiO₂, análoga ao CO₂ do mesmo grupo."},
    {"name": "Óxido de zinco", "formula": "ZnO", "cls": "oxido", "tier": "medio", "traps": ["ZnO_2", "Zn_2O", "Zn(OH)_2"], "why": "Zinco +2 e oxigênio −2: ZnO."},
    {"name": "Dióxido de chumbo", "formula": "PbO_2", "cls": "oxido", "tier": "medio", "traps": ["PbO", "Pb_2O", "PbO_3"], "why": "Chumbo IV com 2 oxigênios: PbO₂, da bateria de carro."},
    {"name": "Glicose", "formula": "C_6H_{12}O_6", "cls": "organico", "tier": "dificil", "traps": ["C_6H_6O_6", "C_{12}H_{22}O_{11}", "C_6H_{10}O_5"], "why": "Glicose: 6 C, 12 H e 6 O; sacarose é C₁₂H₂₂O₁₁."},
    {"name": "Sacarose", "formula": "C_{12}H_{22}O_{11}", "cls": "organico", "tier": "dificil", "traps": ["C_6H_{12}O_6", "C_{12}H_{24}O_{12}", "C_{12}H_{22}O_{12}"], "why": "Sacarose = 2 açúcares menos uma água: C₁₂H₂₂O₁₁."},
    {"name": "Etanol", "formula": "C_2H_5OH", "cls": "organico", "tier": "dificil", "traps": ["CH_3OH", "C_3H_7OH", "C_2H_5O"], "why": "Etanol tem 2 carbonos: C₂H₅OH; CH₃OH é o metanol."},
    {"name": "Metanol", "formula": "CH_3OH", "cls": "organico", "tier": "dificil", "traps": ["C_2H_5OH", "CH_4O_2", "CH_2OH"], "why": "Metanol tem 1 carbono: CH₃OH, álcool tóxico."},
    {"name": "Ácido acético (vinagre)", "formula": "CH_3COOH", "cls": "organico", "tier": "dificil", "traps": ["HCOOH", "CH_3CHO", "C_2H_5OH"], "why": "Ácido acético: 2 carbonos com grupo COOH, CH₃COOH."},
    {"name": "Propano", "formula": "C_3H_8", "cls": "organico", "tier": "dificil", "traps": ["C_3H_6", "C_4H_{10}", "C_2H_6"], "why": "Alcano com 3 carbonos: 2·3+2 = 8 hidrogênios, C₃H₈."},
    {"name": "Butano", "formula": "C_4H_{10}", "cls": "organico", "tier": "dificil", "traps": ["C_4H_8", "C_3H_8", "C_4H_{12}"], "why": "Butano: 4 carbonos e 2·4+2 = 10 hidrogênios, C₄H₁₀."},
    {"name": "Etileno (eteno)", "formula": "C_2H_4", "cls": "organico", "tier": "dificil", "traps": ["C_2H_6", "C_2H_2", "CH_4"], "why": "Eteno tem ligação dupla: C₂H₄; etano é C₂H₆."},
    {"name": "Acetileno (etino)", "formula": "C_2H_2", "cls": "organico", "tier": "dificil", "traps": ["C_2H_4", "C_2H_6", "CH_2"], "why": "Acetileno tem ligação tripla: C₂H₂, gás da solda."},
    {"name": "Benzeno", "formula": "C_6H_6", "cls": "organico", "tier": "dificil", "traps": ["C_6H_{12}", "C_6H_{14}", "C_6H_5"], "why": "Benzeno: anel de 6 carbonos com 6 hidrogênios, C₆H₆."},
    {"name": "Ureia", "formula": "(NH_2)_2CO", "cls": "organico", "tier": "dificil", "traps": ["(NH_4)_2CO_3", "NH_2COOH", "NH_2CO"], "why": "Ureia: dois grupos NH₂ ligados a um C=O, (NH₂)₂CO."},
    {"name": "Ácido cítrico", "formula": "C_6H_8O_7", "cls": "organico", "tier": "dificil", "traps": ["C_6H_{12}O_6", "C_6H_8O_6", "C_6H_{10}O_7"], "why": "Ácido cítrico: C₆H₈O₇; C₆H₈O₆ é a vitamina C."},
    {"name": "Cafeína", "formula": "C_8H_{10}N_4O_2", "cls": "organico", "tier": "dificil", "traps": ["C_8H_{10}N_2O_4", "C_7H_8N_4O_2", "C_8H_{12}N_4O_2"], "why": "Cafeína: C₈H₁₀N₄O₂, com 4 nitrogênios."},
    {"name": "Ácido lático", "formula": "C_3H_6O_3", "cls": "organico", "tier": "dificil", "traps": ["C_3H_8O_3", "C_2H_4O_2", "C_3H_6O_2"], "why": "Ácido lático (formado no músculo em esforço intenso): C₃H₆O₃."},
    {"name": "Glicerol (glicerina)", "formula": "C_3H_8O_3", "cls": "organico", "tier": "dificil", "traps": ["C_3H_6O_3", "C_3H_8O", "C_2H_6O_2"], "why": "Glicerol: 3 carbonos e 3 hidroxilas, C₃H₈O₃."},
    {"name": "Acetona", "formula": "C_3H_6O", "cls": "organico", "tier": "dificil", "traps": ["C_3H_8O", "C_2H_4O", "C_3H_6O_2"], "why": "Acetona (propanona): C₃H₆O, cetona de 3 carbonos."},
    {"name": "Ácido fórmico", "formula": "HCOOH", "cls": "organico", "tier": "dificil", "traps": ["CH_3COOH", "HCHO", "CH_3OH"], "why": "Ácido fórmico, o ácido carboxílico mais simples: HCOOH, da formiga."},
    {"name": "Íon amônio", "formula": "NH_4^+", "cls": "outro", "tier": "dificil", "traps": ["NH_3", "NH_4", "NH_3^+"], "why": "Amônio: NH₃ + H⁺ = NH₄⁺, com carga positiva."},
    {"name": "Sulfato de amônio", "formula": "(NH_4)_2SO_4", "cls": "sal", "tier": "dificil", "traps": ["NH_4SO_4", "(NH_4)_2SO_3", "(NH_3)_2SO_4"], "why": "Amônio NH₄⁺ é +1 e sulfato é −2: (NH₄)₂SO₄."},
    {"name": "Permanganato de potássio", "formula": "KMnO_4", "cls": "sal", "tier": "dificil", "traps": ["KMnO_3", "K_2MnO_4", "KMn_2O_4"], "why": "Permanganato é MnO₄⁻: KMnO₄, de cor roxa intensa."}
  ],
  physics: [
    {"name": "Velocidade média", "lhs": "v_m", "rhs": "Δs/Δt", "tier": 1, "traps": ["Δt/Δs", "Δs·Δt", "Δs/Δt^2"], "why": "Velocidade média é o deslocamento dividido pelo tempo gasto.", "unit": "m/s", "unit_traps": ["m/s^2", "m", "s"]},
    {"name": "Aceleração média", "lhs": "a_m", "rhs": "Δv/Δt", "tier": 1, "traps": ["Δv·Δt", "Δt/Δv", "Δs/Δt"], "why": "Aceleração é a variação da velocidade dividida pelo tempo.", "unit": "m/s^2", "unit_traps": ["m/s", "N", "m"]},
    {"name": "2ª lei de Newton", "lhs": "F_R", "rhs": "m·a", "tier": 1, "traps": ["m·v", "m/a", "m·a^2"], "why": "Força resultante é massa vezes aceleração (não velocidade).", "unit": "N", "unit_traps": ["kg", "J", "m/s^2"]},
    {"name": "Peso", "lhs": "P", "rhs": "m·g", "tier": 1, "traps": ["m/g", "m·g^2", "m·g/2"], "why": "Peso é a massa vezes a aceleração da gravidade.", "unit": "N", "unit_traps": ["kg", "J", "Pa"]},
    {"name": "Densidade", "lhs": "ρ", "rhs": "m/V", "tier": 1, "traps": ["V/m", "m·V", "m·g/V"], "why": "Densidade é massa dividida pelo volume ocupado.", "unit": "kg/m^3", "unit_traps": ["kg", "kg/m^2", "N/m^3"]},
    {"name": "Pressão", "lhs": "p", "rhs": "F/A", "tier": 1, "traps": ["F·A", "A/F", "F/d"], "why": "Pressão é força dividida pela área em que ela atua.", "unit": "Pa", "unit_traps": ["N", "N·m", "J"]},
    {"name": "Frequência", "lhs": "f", "rhs": "1/T", "tier": 1, "traps": ["1/T^2", "T", "2·π·T"], "why": "Frequência é o inverso do período.", "unit": "Hz", "unit_traps": ["s", "rad", "m/s"]},
    {"name": "Período no MCU", "lhs": "T", "rhs": "2·π/ω", "tier": 1, "traps": ["2·π·ω", "π/ω", "1/ω"], "why": "No MCU o período é uma volta (2π rad) dividida pela velocidade angular ω.", "unit": "s", "unit_traps": ["rad/s", "Hz", "rad"]},
    {"name": "Força de atrito", "lhs": "F_{at}", "rhs": "μ·N", "tier": 1, "traps": ["μ·N^2", "N/μ", "μ/N"], "why": "Atrito é o coeficiente μ vezes a força normal N.", "unit": "N", "unit_traps": ["kg", "J", "adimensional"]},
    {"name": "3ª lei de Newton", "lhs": "F_{AB}", "rhs": "-F_{BA}", "tier": 1, "traps": ["F_{BA}", "2·F_{BA}", "F_{BA}/2"], "why": "Ação e reação têm o mesmo módulo e direção, com sentidos opostos.", "unit": "N", "unit_traps": ["kg", "J", "m/s^2"]},
    {"name": "Função horária do MU", "lhs": "s", "rhs": "s_0 + v·t", "tier": 1, "traps": ["s_0 + v·t^2", "s_0·v·t", "s_0 + v/t"], "why": "No MU a posição cresce linearmente: s = s_0 + v·t.", "unit": "m", "unit_traps": ["m/s", "s", "m/s^2"]},
    {"name": "Conversão km/h → m/s", "lhs": "v_{m/s}", "rhs": "v_{km/h}/3,6", "tier": 1, "traps": ["v_{km/h}·3,6", "v_{km/h}/60", "v_{km/h}/1000"], "why": "De km/h para m/s divide por 3,6; de m/s para km/h multiplica.", "unit": "m/s", "unit_traps": ["km/h", "m", "s"]},
    {"name": "Velocidade angular", "lhs": "ω", "rhs": "Δθ/Δt", "tier": 1, "traps": ["Δt/Δθ", "Δθ·Δt", "Δθ/Δt^2"], "why": "Velocidade angular é o ângulo percorrido dividido pelo tempo.", "unit": "rad/s", "unit_traps": ["m/s", "rad", "rad/s^2"]},
    {"name": "Energia cinética", "lhs": "E_c", "rhs": "m·v^2/2", "tier": 2, "traps": ["m·v/2", "m·v^2", "m^2·v/2"], "why": "Energia cinética tem v ao quadrado e divide por 2.", "unit": "J", "unit_traps": ["N", "W", "kg·m/s"]},
    {"name": "Energia potencial gravitacional", "lhs": "E_p", "rhs": "m·g·h", "tier": 2, "traps": ["m·g/h", "m·g·h/2", "m·g·h^2"], "why": "Energia potencial gravitacional é m·g·h, sem dividir por 2.", "unit": "J", "unit_traps": ["N", "W", "Pa"]},
    {"name": "Trabalho de força constante", "lhs": "τ", "rhs": "F·d·cos θ", "tier": 2, "traps": ["F·d·sen θ", "F/d·cos θ", "F·d·tg θ"], "why": "Trabalho usa o cosseno do ângulo entre força e deslocamento.", "unit": "J", "unit_traps": ["N", "W", "N/m"]},
    {"name": "Potência média", "lhs": "Pot", "rhs": "τ/Δt", "tier": 2, "traps": ["τ·Δt", "Δt/τ", "τ/Δt^2"], "why": "Potência é trabalho (ou energia) dividido pelo tempo.", "unit": "W", "unit_traps": ["J", "N", "J·s"]},
    {"name": "Potência e velocidade", "lhs": "Pot", "rhs": "F·v", "tier": 2, "traps": ["F/v", "F·v^2", "F·v/2"], "why": "Potência de uma força é força vezes velocidade.", "unit": "W", "unit_traps": ["J", "N", "N/s"]},
    {"name": "Quantidade de movimento", "lhs": "Q", "rhs": "m·v", "tier": 2, "traps": ["m·v^2", "m·v/2", "m·a"], "why": "Quantidade de movimento é massa vezes velocidade, sem quadrado.", "unit": "kg·m/s", "unit_traps": ["N", "J", "m/s"]},
    {"name": "Impulso", "lhs": "I", "rhs": "F·Δt", "tier": 2, "traps": ["F/Δt", "F·Δt^2", "F·Δs"], "why": "Impulso é força vezes o intervalo de tempo de atuação.", "unit": "N·s", "unit_traps": ["N", "J", "N/s"]},
    {"name": "Teorema do impulso", "lhs": "I", "rhs": "ΔQ", "tier": 2, "traps": ["ΔE_c", "Q·Δt", "m·a"], "why": "O impulso é igual à variação da quantidade de movimento.", "unit": "N·s", "unit_traps": ["J", "W", "kg·m"]},
    {"name": "Lei de Hooke", "lhs": "F_{el}", "rhs": "k·x", "tier": 2, "traps": ["k·x^2", "k/x", "k·x^2/2"], "why": "Força elástica é proporcional à deformação: F = k·x.", "unit": "N", "unit_traps": ["N/m", "J", "m"]},
    {"name": "Energia potencial elástica", "lhs": "E_{pe}", "rhs": "k·x^2/2", "tier": 2, "traps": ["k·x/2", "k·x^2", "k^2·x/2"], "why": "Energia elástica tem x ao quadrado e divide por 2.", "unit": "J", "unit_traps": ["N", "N/m", "W"]},
    {"name": "Energia mecânica", "lhs": "E_m", "rhs": "E_c + E_p", "tier": 2, "traps": ["E_c - E_p", "E_c·E_p", "E_c/E_p"], "why": "Energia mecânica é a soma da cinética com a potencial.", "unit": "J", "unit_traps": ["N", "W", "kg·m/s"]},
    {"name": "Rendimento", "lhs": "η", "rhs": "Pot_u/Pot_t", "tier": 2, "traps": ["Pot_t/Pot_u", "Pot_u - Pot_t", "Pot_u·Pot_t"], "why": "Rendimento é a potência útil dividida pela total, nunca maior que 1.", "unit": "adimensional", "unit_traps": ["W", "J", "N"]},
    {"name": "Teorema da energia cinética", "lhs": "τ_R", "rhs": "ΔE_c", "tier": 2, "traps": ["ΔE_p", "ΔQ", "E_c·Δt"], "why": "O trabalho da força resultante é igual à variação da energia cinética.", "unit": "J", "unit_traps": ["N", "W", "N·s"]},
    {"name": "Trabalho da força peso", "lhs": "τ_P", "rhs": "m·g·h", "tier": 2, "traps": ["m·g/h", "m·g·h/2", "m·h"], "why": "Trabalho do peso é m·g·h e só depende do desnível h.", "unit": "J", "unit_traps": ["N", "W", "Pa"]},
    {"name": "Energia cinética e momento", "lhs": "E_c", "rhs": "Q^2/(2·m)", "tier": 2, "traps": ["Q^2/m", "Q/(2·m)", "Q^2·m/2"], "why": "Como Q = m·v, E_c = m·v^2/2 vira Q^2/(2·m).", "unit": "J", "unit_traps": ["N·s", "W", "kg·m/s"]},
    {"name": "Equação fundamental da ondulatória", "lhs": "v", "rhs": "λ·f", "tier": 3, "traps": ["λ/f", "f/λ", "λ·T"], "why": "Velocidade da onda é comprimento de onda vezes frequência.", "unit": "m/s", "unit_traps": ["m", "Hz", "m/s^2"]},
    {"name": "1ª lei de Ohm", "lhs": "U", "rhs": "R·i", "tier": 3, "traps": ["R/i", "i/R", "R·i^2"], "why": "Tensão é resistência vezes corrente: U = R·i.", "unit": "V", "unit_traps": ["A", "Ω", "W"]},
    {"name": "Potência elétrica", "lhs": "Pot_{el}", "rhs": "U·i", "tier": 3, "traps": ["U/i", "U·i^2", "U^2·i"], "why": "Potência elétrica é tensão vezes corrente.", "unit": "W", "unit_traps": ["V", "J", "A"]},
    {"name": "Efeito Joule (R·i^2)", "lhs": "P_{el}", "rhs": "R·i^2", "tier": 3, "traps": ["R·i", "R^2·i", "R/i^2"], "why": "Substituindo U = R·i em P = U·i, fica P = R·i^2.", "unit": "W", "unit_traps": ["V", "Ω", "J"]},
    {"name": "Potência elétrica (U^2/R)", "lhs": "P_{el}", "rhs": "U^2/R", "tier": 3, "traps": ["U/R", "R/U^2", "U^2·R"], "why": "Substituindo i = U/R em P = U·i, fica P = U^2/R.", "unit": "W", "unit_traps": ["V", "Ω", "J"]},
    {"name": "Calor sensível", "lhs": "Q", "rhs": "m·c·Δθ", "tier": 3, "traps": ["m·c/Δθ", "m·L", "c·Δθ"], "why": "Calor sensível muda a temperatura: Q = m·c·Δθ.", "unit": "J", "unit_traps": ["W", "J/kg", "J/(kg·°C)"]},
    {"name": "Calor latente", "lhs": "Q", "rhs": "m·L", "tier": 3, "traps": ["m·c·Δθ", "m/L", "L/m"], "why": "Calor latente muda o estado sem mudar a temperatura: Q = m·L.", "unit": "J", "unit_traps": ["W", "J/kg", "K"]},
    {"name": "Força centrípeta", "lhs": "F_{cp}", "rhs": "m·v^2/R", "tier": 3, "traps": ["m·v/R", "m·v^2·R", "m·v^2/(2·R)"], "why": "Força centrípeta tem v ao quadrado dividido pelo raio, sem o 2.", "unit": "N", "unit_traps": ["J", "m/s^2", "kg"]},
    {"name": "Empuxo", "lhs": "E", "rhs": "ρ_f·V_i·g", "tier": 3, "traps": ["ρ_f·V_i/g", "ρ_c·V_i·g", "ρ_f·g"], "why": "Empuxo usa a densidade do fluido e o volume imerso: ρ_f·V_i·g.", "unit": "N", "unit_traps": ["kg", "Pa", "J"]},
    {"name": "Pressão hidrostática", "lhs": "p", "rhs": "ρ·g·h", "tier": 3, "traps": ["ρ·g/h", "ρ·h", "ρ·g·h^2"], "why": "Pressão da coluna de líquido é densidade vezes g vezes profundidade.", "unit": "Pa", "unit_traps": ["N", "kg/m^3", "J"]},
    {"name": "Lei de Stevin", "lhs": "p", "rhs": "p_0 + ρ·g·h", "tier": 3, "traps": ["p_0 - ρ·g·h", "p_0·ρ·g·h", "p_0 + ρ·h"], "why": "Pressão total é a atmosférica mais a da coluna: p_0 + ρ·g·h.", "unit": "Pa", "unit_traps": ["N", "J", "kg/m^3"]},
    {"name": "Período do pêndulo simples", "lhs": "T", "rhs": "2·π·√(L/g)", "tier": 3, "traps": ["2·π·√(g/L)", "2·π·√(L·g)", "2·π·L/g"], "why": "Pêndulo: raiz de L sobre g; não depende da massa.", "unit": "s", "unit_traps": ["Hz", "m", "m/s"]},
    {"name": "Período do sistema massa-mola", "lhs": "T", "rhs": "2·π·√(m/k)", "tier": 3, "traps": ["2·π·√(k/m)", "2·π·m/k", "2·π·√(m·k)"], "why": "Massa-mola: raiz de m sobre k; mola mais dura, período menor.", "unit": "s", "unit_traps": ["Hz", "N/m", "kg"]},
    {"name": "2ª lei de Ohm", "lhs": "R", "rhs": "ρ·L/A", "tier": 3, "traps": ["ρ·A/L", "ρ·L·A", "L/(ρ·A)"], "why": "Resistência cresce com o comprimento e diminui com a área.", "unit": "Ω", "unit_traps": ["V", "A", "Ω·m"]},
    {"name": "Resistores em série", "lhs": "R_{eq}", "rhs": "R_1 + R_2", "tier": 3, "traps": ["R_1·R_2/(R_1+R_2)", "R_1·R_2", "1/R_1 + 1/R_2"], "why": "Em série as resistências simplesmente se somam.", "unit": "Ω", "unit_traps": ["V", "A", "W"]},
    {"name": "Resistores em paralelo", "lhs": "R_{eq}", "rhs": "R_1·R_2/(R_1+R_2)", "tier": 3, "traps": ["R_1 + R_2", "(R_1+R_2)/(R_1·R_2)", "R_1·R_2"], "why": "Paralelo de dois resistores: produto sobre a soma.", "unit": "Ω", "unit_traps": ["V", "A", "W"]},
    {"name": "Carga do capacitor", "lhs": "Q", "rhs": "C·U", "tier": 3, "traps": ["C/U", "U/C", "C·U^2/2"], "why": "Da definição C = Q/U, a carga é Q = C·U (C·U²/2 é a energia).", "unit": "C", "unit_traps": ["F", "V", "A"]},
    {"name": "Equação de Gauss (lentes)", "lhs": "1/f", "rhs": "1/p + 1/p'", "tier": 3, "traps": ["1/p - 1/p'", "p + p'", "p·p'/(p+p')"], "why": "Gauss: os inversos se somam, 1/f = 1/p + 1/p'.", "unit": "1/m", "unit_traps": ["m", "cm", "adimensional"]},
    {"name": "Dilatação linear", "lhs": "ΔL", "rhs": "L_0·α·Δθ", "tier": 3, "traps": ["L_0·α/Δθ", "α·Δθ", "L_0·α·Δθ^2"], "why": "Dilatação depende do tamanho inicial, do material (α) e do Δθ.", "unit": "m", "unit_traps": ["°C", "m/°C", "adimensional"]},
    {"name": "Gravitação universal", "lhs": "F", "rhs": "G·M·m/d^2", "tier": 4, "traps": ["G·M·m/d", "G·M/d^2", "G·M·m·d^2"], "why": "Força gravitacional: produto das massas sobre a distância ao quadrado.", "unit": "N", "unit_traps": ["J", "m/s^2", "kg"]},
    {"name": "Lei de Coulomb", "lhs": "F", "rhs": "k·Q·q/d^2", "tier": 4, "traps": ["k·Q·q/d", "k·Q/d^2", "k·Q·q·d^2"], "why": "Coulomb: produto das cargas sobre a distância ao quadrado.", "unit": "N", "unit_traps": ["C", "V", "N/C"]},
    {"name": "Equação de Torricelli", "lhs": "v^2", "rhs": "v_0^2 + 2·a·Δs", "tier": 4, "traps": ["v_0^2 + a·Δs", "v_0 + 2·a·Δs", "v_0^2 + 2·a·Δs^2"], "why": "Torricelli: v^2 = v_0^2 + 2·a·Δs, sem o tempo.", "unit": "m^2/s^2", "unit_traps": ["m/s", "m/s^2", "m^2/s"]},
    {"name": "MUV – velocidade", "lhs": "v", "rhs": "v_0 + a·t", "tier": 4, "traps": ["v_0 + a·t^2", "v_0 + a·t/2", "v_0·a·t"], "why": "No MUV a velocidade cresce linearmente: v = v_0 + a·t.", "unit": "m/s", "unit_traps": ["m", "m/s^2", "s"]},
    {"name": "MUV – posição", "lhs": "s", "rhs": "s_0 + v_0·t + a·t^2/2", "tier": 4, "traps": ["s_0 + v_0·t + a·t^2", "s_0 + v_0·t + a·t/2", "s_0 + v_0·t^2 + a·t/2"], "why": "Função horária do MUV: o termo da aceleração é a·t^2/2.", "unit": "m", "unit_traps": ["m/s", "s", "m/s^2"]},
    {"name": "Equação de Clapeyron", "lhs": "p·V", "rhs": "n·R·T", "tier": 4, "traps": ["n·R/T", "n·T/R", "n·R·T^2"], "why": "Gás ideal: p·V = n·R·T, com T em kelvin.", "unit": "J", "unit_traps": ["Pa", "K", "mol"]},
    {"name": "1ª lei da termodinâmica", "lhs": "ΔU", "rhs": "Q - τ", "tier": 4, "traps": ["Q + τ", "τ - Q", "Q·τ"], "why": "Energia interna: calor recebido menos trabalho realizado pelo gás.", "unit": "J", "unit_traps": ["K", "W", "Pa"]},
    {"name": "Lei de Snell", "lhs": "n_1·sen θ_1", "rhs": "n_2·sen θ_2", "tier": 4, "traps": ["n_2·cos θ_2", "n_2/sen θ_2", "n_1·sen θ_2"], "why": "Snell: n·sen θ é o mesmo nos dois meios.", "unit": "adimensional", "unit_traps": ["rad", "m/s", "m"]},
    {"name": "Energia do fóton", "lhs": "E", "rhs": "h·f", "tier": 4, "traps": ["h/f", "h·λ", "h·f^2"], "why": "Energia do fóton é a constante de Planck vezes a frequência.", "unit": "J", "unit_traps": ["W", "Hz", "J·s"]},
    {"name": "Equivalência massa-energia", "lhs": "E", "rhs": "m·c^2", "tier": 4, "traps": ["m·c", "m·c^2/2", "m^2·c"], "why": "Einstein: E = m·c^2, com c ao quadrado e sem dividir por 2.", "unit": "J", "unit_traps": ["kg", "W", "N"]},
    {"name": "Campo elétrico", "lhs": "E", "rhs": "F/q", "tier": 4, "traps": ["F·q", "q/F", "F/q^2"], "why": "Campo elétrico é força por unidade de carga de prova.", "unit": "N/C", "unit_traps": ["N", "C", "V"]},
    {"name": "Campo de carga puntiforme", "lhs": "E", "rhs": "k·Q/d^2", "tier": 4, "traps": ["k·Q/d", "k·Q·q/d^2", "k·Q^2/d^2"], "why": "Campo de uma carga: k·Q/d^2; com q vira força, com d vira potencial.", "unit": "N/C", "unit_traps": ["N", "V", "C"]},
    {"name": "Alcance do lançamento oblíquo", "lhs": "A", "rhs": "v_0^2·sen(2θ)/g", "tier": 4, "traps": ["v_0^2·sen θ/g", "v_0·sen(2θ)/g", "v_0^2·cos(2θ)/g"], "why": "Alcance usa sen(2θ): máximo em 45°.", "unit": "m", "unit_traps": ["m/s", "s", "m/s^2"]},
    {"name": "Velocidade orbital", "lhs": "v", "rhs": "√(G·M/r)", "tier": 4, "traps": ["√(G·M/r^2)", "G·M/r", "√(G·M·r)"], "why": "Igualando gravidade e centrípeta: v = √(G·M/r).", "unit": "m/s", "unit_traps": ["m/s^2", "m", "N"]},
    {"name": "Rendimento de Carnot", "lhs": "η", "rhs": "1 - T_F/T_Q", "tier": 4, "traps": ["1 - T_Q/T_F", "T_F/T_Q", "1 + T_F/T_Q"], "why": "Carnot: 1 menos a razão fria/quente (T_F/T_Q), em kelvin.", "unit": "adimensional", "unit_traps": ["K", "J", "W"]},
    {"name": "Potencial de carga puntiforme", "lhs": "V", "rhs": "k·Q/d", "tier": 4, "traps": ["k·Q/d^2", "k·Q·d", "k·Q^2/d"], "why": "Potencial cai com d (sem quadrado); o campo cai com d^2.", "unit": "V", "unit_traps": ["N/C", "J", "C"]}
  ],
  bio: [
    {"title": "Coração", "text": "Sistema", "ans": "Circulatório", "traps": ["Respiratório", "Digestório", "Nervoso"], "why": "O coração bombeia o sangue pelos vasos do sistema circulatório.", "tier": 1},
    {"title": "Pulmão", "text": "Sistema", "ans": "Respiratório", "traps": ["Circulatório", "Digestório", "Urinário"], "why": "Nos pulmões o sangue recebe oxigênio e libera gás carbônico.", "tier": 1},
    {"title": "Estômago", "text": "Sistema", "ans": "Digestório", "traps": ["Respiratório", "Urinário", "Circulatório"], "why": "No estômago, o suco gástrico começa a digestão das proteínas.", "tier": 1},
    {"title": "Bexiga", "text": "Sistema", "ans": "Urinário", "traps": ["Digestório", "Circulatório", "Respiratório"], "why": "A bexiga armazena a urina produzida pelos rins até ser eliminada.", "tier": 1},
    {"title": "Cérebro", "text": "Sistema", "ans": "Nervoso", "traps": ["Muscular", "Respiratório", "Digestório"], "why": "O cérebro faz parte do sistema nervoso e comanda o corpo.", "tier": 1},
    {"title": "Raiz", "text": "Função", "ans": "Absorver água e sais", "traps": ["Fazer fotossíntese", "Produzir sementes", "Atrair polinizadores"], "why": "A raiz fixa a planta e absorve água e sais minerais do solo.", "tier": 1},
    {"title": "Folha", "text": "Função principal", "ans": "Fotossíntese", "traps": ["Absorver água do solo", "Produzir sementes", "Fixar a planta"], "why": "Nas folhas, a clorofila capta a luz usada para produzir alimento.", "tier": 1},
    {"title": "Flor", "text": "Função", "ans": "Reprodução", "traps": ["Fotossíntese", "Absorção de água", "Sustentação"], "why": "A flor é o órgão reprodutor das plantas angiospermas.", "tier": 1},
    {"title": "Fruto", "text": "Função", "ans": "Proteger a semente", "traps": ["Fazer fotossíntese", "Absorver água", "Produzir pólen"], "why": "O fruto protege a semente e ajuda a espalhá-la pelo ambiente.", "tier": 1},
    {"title": "Semente", "text": "Função", "ans": "Originar nova planta", "traps": ["Fazer fotossíntese", "Sustentar a planta", "Atrair polinizadores"], "why": "A semente guarda o embrião, que germina e forma uma nova planta.", "tier": 1},
    {"title": "Morcego", "text": "Classe", "ans": "Mamíferos", "traps": ["Aves", "Répteis", "Anfíbios"], "why": "O morcego voa, mas tem pelos e amamenta: é um mamífero.", "tier": 1},
    {"title": "Pinguim", "text": "Classe", "ans": "Aves", "traps": ["Mamíferos", "Peixes", "Anfíbios"], "why": "O pinguim não voa, mas tem penas e bico: é uma ave.", "tier": 1},
    {"title": "Sapo", "text": "Classe", "ans": "Anfíbios", "traps": ["Répteis", "Peixes", "Mamíferos"], "why": "O sapo passa pela fase de girino na água e tem pele sem escamas: é anfíbio.", "tier": 1},
    {"title": "Jacaré", "text": "Classe", "ans": "Répteis", "traps": ["Anfíbios", "Mamíferos", "Peixes"], "why": "O jacaré tem pele com escamas e põe ovos com casca.", "tier": 1},
    {"title": "Tubarão", "text": "Grupo", "ans": "Peixes", "traps": ["Mamíferos", "Répteis", "Anfíbios"], "why": "O tubarão respira por brânquias e tem nadadeiras: é um peixe.", "tier": 1},
    {"title": "Cogumelo", "text": "Reino", "ans": "Fungi", "traps": ["Plantae", "Monera", "Protista"], "why": "Cogumelos são fungos: não fazem fotossíntese e absorvem nutrientes do meio.", "tier": 1},
    {"title": "Capim", "text": "Nível trófico", "ans": "Produtor", "traps": ["Consumidor primário", "Decompositor", "Consumidor secundário"], "why": "O capim faz fotossíntese e produz o próprio alimento.", "tier": 1},
    {"title": "Coelho", "text": "Nível trófico", "ans": "Consumidor primário", "traps": ["Produtor", "Decompositor", "Consumidor secundário"], "why": "O coelho come plantas, por isso é consumidor primário.", "tier": 1},
    {"title": "Unidade básica da vida", "text": "Nome", "ans": "Célula", "traps": ["Tecido", "Órgão", "Molécula"], "why": "Todos os seres vivos são formados por uma ou mais células.", "tier": 1},
    {"title": "Fotossíntese", "text": "Gás liberado", "ans": "Oxigênio", "traps": ["Gás carbônico", "Nitrogênio", "Metano"], "why": "Na fotossíntese a planta usa gás carbônico e água e libera oxigênio.", "tier": 1},
    {"title": "Pigmento verde das plantas", "text": "Nome", "ans": "Clorofila", "traps": ["Hemoglobina", "Melanina", "Amido"], "why": "A clorofila absorve luz para a fotossíntese e dá a cor verde.", "tier": 1},
    {"title": "Núcleo", "text": "Função", "ans": "Abrigar o DNA", "traps": ["Produzir energia", "Fazer fotossíntese", "Digerir partículas"], "why": "O núcleo guarda o DNA e controla as atividades da célula.", "tier": 2},
    {"title": "Mitocôndria", "text": "Função", "ans": "Respiração celular", "traps": ["Fotossíntese", "Armazenar água", "Digestão celular"], "why": "Na mitocôndria ocorre a maior parte da respiração celular, que gera ATP.", "tier": 2},
    {"title": "Faz a fotossíntese", "text": "Organela", "ans": "Cloroplasto", "traps": ["Mitocôndria", "Ribossomo", "Lisossomo"], "why": "O cloroplasto tem clorofila, que capta luz para produzir glicose.", "tier": 2},
    {"title": "Membrana plasmática", "text": "Função", "ans": "Controlar o que entra", "traps": ["Produzir proteínas", "Guardar o DNA", "Fazer fotossíntese"], "why": "A membrana controla o que entra e o que sai da célula.", "tier": 2},
    {"title": "Fígado", "text": "Sistema", "ans": "Digestório", "traps": ["Urinário", "Respiratório", "Nervoso"], "why": "O fígado produz a bile, que ajuda na digestão das gorduras.", "tier": 2},
    {"title": "Medula espinal", "text": "Sistema", "ans": "Nervoso", "traps": ["Esquelético", "Circulatório", "Digestório"], "why": "A medula espinal fica dentro da coluna e conduz impulsos nervosos.", "tier": 2},
    {"title": "Hemácia", "text": "Função", "ans": "Transportar oxigênio", "traps": ["Defender o corpo", "Coagular o sangue", "Produzir anticorpos"], "why": "A hemácia tem hemoglobina, que leva oxigênio a todo o corpo.", "tier": 2},
    {"title": "Caule", "text": "Função", "ans": "Sustentar e conduzir", "traps": ["Absorver água do solo", "Produzir sementes", "Atrair polinizadores"], "why": "O caule sustenta a planta e leva a seiva entre raiz e folhas.", "tier": 2},
    {"title": "Golfinho", "text": "Classe", "ans": "Mamíferos", "traps": ["Peixes", "Anfíbios", "Répteis"], "why": "O golfinho respira por pulmões e amamenta: é um mamífero.", "tier": 2},
    {"title": "Cavalo-marinho", "text": "Grupo", "ans": "Peixes", "traps": ["Mamíferos", "Répteis", "Anfíbios"], "why": "O cavalo-marinho tem brânquias e nadadeiras: é um peixe.", "tier": 2},
    {"title": "Bactéria", "text": "Reino", "ans": "Monera", "traps": ["Fungi", "Protista", "Plantae"], "why": "Bactérias são procariontes, sem núcleo: pertencem ao reino Monera.", "tier": 2},
    {"title": "Coral", "text": "Reino", "ans": "Animalia", "traps": ["Plantae", "Protista", "Monera"], "why": "Corais são animais (cnidários), apesar de parecerem rochas ou plantas.", "tier": 2},
    {"title": "Louis Pasteur", "text": "Criou", "ans": "Pasteurização", "traps": ["Penicilina", "Seleção natural", "Leis da herança"], "why": "Pasteur mostrou que micróbios estragam alimentos e criou a pasteurização.", "tier": 2},
    {"title": "Fungos em tronco podre", "text": "Papel ecológico", "ans": "Decompositor", "traps": ["Produtor", "Consumidor primário", "Predador"], "why": "Fungos decompõem matéria morta e devolvem nutrientes ao solo.", "tier": 2},
    {"title": "Piolho na cabeça", "text": "Relação", "ans": "Parasitismo", "traps": ["Mutualismo", "Comensalismo", "Predação"], "why": "O piolho suga sangue do hospedeiro e o prejudica: é parasita.", "tier": 2},
    {"title": "Falta de vitamina C", "text": "Doença", "ans": "Escorbuto", "traps": ["Raquitismo", "Beribéri", "Cegueira noturna"], "why": "Sem vitamina C, as gengivas sangram; frutas cítricas previnem o escorbuto.", "tier": 2},
    {"title": "Falta de ferro", "text": "Doença", "ans": "Anemia", "traps": ["Bócio", "Escorbuto", "Raquitismo"], "why": "O ferro faz parte da hemoglobina, que leva oxigênio no sangue.", "tier": 2},
    {"title": "Insulina", "text": "Glândula", "ans": "Pâncreas", "traps": ["Tireoide", "Hipófise", "Fígado"], "why": "A insulina, do pâncreas, faz a glicose passar do sangue às células.", "tier": 2},
    {"title": "Testosterona", "text": "Glândula", "ans": "Testículos", "traps": ["Hipófise", "Tireoide", "Pâncreas"], "why": "Os testículos produzem testosterona e espermatozoides.", "tier": 2},
    {"title": "Charles Darwin", "text": "Conhecido por", "ans": "Seleção natural", "traps": ["Leis da herança", "Penicilina", "Pasteurização"], "why": "Darwin explicou a evolução das espécies pela seleção natural.", "tier": 2},
    {"title": "Alexander Fleming", "text": "Descobriu", "ans": "Penicilina", "traps": ["Vacina da raiva", "Seleção natural", "Leis da herança"], "why": "Fleming viu que um fungo, o Penicillium, matava bactérias.", "tier": 2},
    {"title": "Síntese de proteínas", "text": "Organela", "ans": "Ribossomo", "traps": ["Lisossomo", "Complexo de Golgi", "Centríolo"], "why": "Ribossomos leem o RNA e unem aminoácidos formando proteínas.", "tier": 3},
    {"title": "Lisossomo", "text": "Função", "ans": "Digestão celular", "traps": ["Síntese de proteínas", "Respiração celular", "Fotossíntese"], "why": "Lisossomos têm enzimas que digerem partículas e restos da célula.", "tier": 3},
    {"title": "Célula de bactéria", "text": "Tipo de célula", "ans": "Procarionte", "traps": ["Eucarionte", "Acelular", "Célula vegetal"], "why": "Bactérias são procariontes: o DNA fica solto, sem núcleo definido.", "tier": 3},
    {"title": "Estômato", "text": "Função", "ans": "Trocas gasosas", "traps": ["Absorver água do solo", "Fixar a planta", "Formar pólen"], "why": "Estômatos são poros das folhas por onde entram e saem gases.", "tier": 3},
    {"title": "Xilema", "text": "Transporta", "ans": "Seiva bruta", "traps": ["Seiva elaborada", "Néctar", "Látex"], "why": "O xilema leva água e sais minerais da raiz até as folhas.", "tier": 3},
    {"title": "Samambaia", "text": "Grupo", "ans": "Pteridófitas", "traps": ["Briófitas", "Gimnospermas", "Angiospermas"], "why": "Samambaias têm vasos condutores, mas não têm sementes nem flores.", "tier": 3},
    {"title": "Ornitorrinco", "text": "Classe", "ans": "Mamíferos", "traps": ["Aves", "Répteis", "Anfíbios"], "why": "O ornitorrinco põe ovos, mas tem pelos e amamenta: é mamífero.", "tier": 3},
    {"title": "Ameba", "text": "Reino", "ans": "Protista", "traps": ["Monera", "Fungi", "Animalia"], "why": "A ameba é um protozoário, unicelular e eucarionte: reino Protista.", "tier": 3},
    {"title": "Sapo (capim → grilo → sapo)", "text": "Nível trófico", "ans": "Consumidor secundário", "traps": ["Consumidor primário", "Produtor", "Decompositor"], "why": "O sapo come o grilo, que come o capim: é consumidor secundário.", "tier": 3},
    {"title": "Líquen (alga + fungo)", "text": "Relação", "ans": "Mutualismo", "traps": ["Comensalismo", "Predação", "Competição"], "why": "No líquen, a alga faz fotossíntese e o fungo dá proteção e água: ambos ganham.", "tier": 3},
    {"title": "Formigas de um formigueiro", "text": "Relação", "ans": "Sociedade", "traps": ["Comensalismo", "Predação", "Parasitismo"], "why": "Na sociedade, indivíduos separados dividem tarefas, como as formigas.", "tier": 3},
    {"title": "Falta de vitamina D", "text": "Doença", "ans": "Raquitismo", "traps": ["Escorbuto", "Beribéri", "Cegueira noturna"], "why": "A vitamina D ajuda a absorver cálcio; sem ela, os ossos das crianças enfraquecem.", "tier": 3},
    {"title": "Falta de iodo", "text": "Doença", "ans": "Bócio", "traps": ["Anemia", "Raquitismo", "Escorbuto"], "why": "Sem iodo, a tireoide aumenta de volume (bócio); por isso o sal é iodado.", "tier": 3},
    {"title": "Adrenalina", "text": "Glândula", "ans": "Suprarrenal", "traps": ["Tireoide", "Hipófise", "Pâncreas"], "why": "A adrenalina, das suprarrenais, prepara o corpo para luta ou fuga.", "tier": 3},
    {"title": "Adenina (DNA)", "text": "Pareia com", "ans": "Timina", "traps": ["Uracila", "Citosina", "Guanina"], "why": "No DNA, adenina pareia com timina e citosina com guanina.", "tier": 3},
    {"title": "Genótipo Aa", "text": "Classificação", "ans": "Heterozigoto", "traps": ["Homozigoto dominante", "Homozigoto recessivo", "Haploide"], "why": "Aa tem dois alelos diferentes para o gene: é heterozigoto.", "tier": 3},
    {"title": "Característica observável", "text": "Nome", "ans": "Fenótipo", "traps": ["Genótipo", "Alelo", "Cariótipo"], "why": "Fenótipo é o que se observa; genótipo é a composição genética.", "tier": 3},
    {"title": "Alelo só expresso em dose dupla", "text": "Tipo de alelo", "ans": "Recessivo", "traps": ["Dominante", "Codominante", "Heterozigoto"], "why": "O alelo recessivo só aparece no fenótipo quando está em dose dupla (aa).", "tier": 3},
    {"title": "Mitose", "text": "Resultado", "ans": "2 células iguais", "traps": ["4 células diferentes", "2 células diferentes", "4 células iguais"], "why": "A mitose gera duas células idênticas à célula-mãe.", "tier": 3},
    {"title": "Meiose em animais", "text": "Produz", "ans": "Gametas", "traps": ["Células somáticas", "Células-tronco", "Hemácias"], "why": "A meiose reduz os cromossomos à metade e forma os gametas.", "tier": 3},
    {"title": "Gregor Mendel", "text": "Conhecido por", "ans": "Leis da herança", "traps": ["Seleção natural", "Penicilina", "Pasteurização"], "why": "Mendel cruzou ervilhas e descobriu como as características são herdadas.", "tier": 3},
    {"title": "Complexo de Golgi", "text": "Função", "ans": "Empacotar e secretar", "traps": ["Respiração celular", "Fotossíntese", "Guardar o DNA"], "why": "O Golgi modifica, empacota e envia substâncias para fora da célula.", "tier": 4},
    {"title": "Retículo endoplasmático liso", "text": "Função", "ans": "Produzir lipídios", "traps": ["Síntese de proteínas", "Fotossíntese", "Digestão celular"], "why": "O retículo liso produz lipídios e ajuda a desintoxicar a célula.", "tier": 4},
    {"title": "Floema", "text": "Transporta", "ans": "Seiva elaborada", "traps": ["Seiva bruta", "Néctar", "Látex"], "why": "O floema leva os açúcares feitos nas folhas para toda a planta.", "tier": 4},
    {"title": "Ovário da flor", "text": "Desenvolve-se em", "ans": "Fruto", "traps": ["Semente", "Pólen", "Embrião"], "why": "Após a fecundação, o ovário vira fruto e os óvulos viram sementes.", "tier": 4},
    {"title": "Semente sem fruto (pinheiro)", "text": "Grupo", "ans": "Gimnospermas", "traps": ["Angiospermas", "Pteridófitas", "Briófitas"], "why": "Gimnospermas têm sementes nuas, sem fruto, como as do pinheiro.", "tier": 4},
    {"title": "Cianobactéria", "text": "Reino", "ans": "Monera", "traps": ["Plantae", "Protista", "Fungi"], "why": "Cianobactérias fazem fotossíntese, mas são procariontes: Monera.", "tier": 4},
    {"title": "Caravela-portuguesa", "text": "Relação", "ans": "Colônia", "traps": ["Sociedade", "Mutualismo", "Parasitismo"], "why": "A caravela é formada por indivíduos unidos fisicamente: é uma colônia.", "tier": 4},
    {"title": "Rêmora e tubarão", "text": "Relação", "ans": "Comensalismo", "traps": ["Parasitismo", "Predação", "Competição"], "why": "A rêmora come restos da caça do tubarão sem prejudicá-lo: é comensalismo.", "tier": 4},
    {"title": "Falta de vitamina B1", "text": "Doença", "ans": "Beribéri", "traps": ["Escorbuto", "Raquitismo", "Pelagra"], "why": "A falta de vitamina B1 (tiamina) causa beribéri, que afeta os nervos.", "tier": 4},
    {"title": "Vitamina K", "text": "Função", "ans": "Coagulação do sangue", "traps": ["Visão noturna", "Formação de colágeno", "Prevenir o escorbuto"], "why": "A vitamina K é necessária para produzir fatores de coagulação.", "tier": 4},
    {"title": "Glucagon", "text": "Efeito", "ans": "Aumenta a glicemia", "traps": ["Reduz a glicemia", "Acelera a digestão", "Estimula a ovulação"], "why": "O glucagon faz o fígado liberar glicose quando o açúcar do sangue cai.", "tier": 4},
    {"title": "ADH (antidiurético)", "text": "Efeito", "ans": "Retém água nos rins", "traps": ["Aumenta a urina", "Eleva a glicemia", "Acelera o coração"], "why": "O ADH faz os rins reabsorverem água, deixando a urina concentrada.", "tier": 4},
    {"title": "Adenina (RNA)", "text": "Pareia com", "ans": "Uracila", "traps": ["Timina", "Citosina", "Guanina"], "why": "No RNA não há timina: a adenina pareia com a uracila.", "tier": 4},
    {"title": "Açúcar do DNA", "text": "Nome", "ans": "Desoxirribose", "traps": ["Ribose", "Glicose", "Sacarose"], "why": "O DNA tem desoxirribose; o RNA tem ribose.", "tier": 4},
    {"title": "Aa × Aa (dominância completa)", "text": "Razão fenotípica", "ans": "3:1", "traps": ["1:2:1", "1:1", "9:3:3:1"], "why": "Aa × Aa gera 1 AA : 2 Aa : 1 aa, ou seja, 3 dominantes para 1 recessivo.", "tier": 4},
    {"title": "Crossing-over (permutação)", "text": "Ocorre na", "ans": "Prófase I da meiose", "traps": ["Telófase da mitose", "Anáfase II da meiose", "Interfase"], "why": "Na prófase I, cromossomos homólogos trocam trechos e geram variabilidade.", "tier": 4},
    {"title": "Cromossomos no equador", "text": "Fase da mitose", "ans": "Metáfase", "traps": ["Prófase", "Anáfase", "Telófase"], "why": "Na metáfase, os cromossomos se alinham no plano equatorial da célula.", "tier": 4},
    {"title": "Síndrome de Down", "text": "Causa", "ans": "Trissomia do 21", "traps": ["Trissomia do 18", "Monossomia do X", "Trissomia do 13"], "why": "Na síndrome de Down há três cópias do cromossomo 21.", "tier": 4},
    {"title": "Tradução (genética)", "text": "Produz", "ans": "Proteína", "traps": ["RNA mensageiro", "DNA", "Glicose"], "why": "Na tradução, o ribossomo lê o RNAm e une aminoácidos em proteína.", "tier": 4},
    {"title": "Lamarck", "text": "Ideia central", "ans": "Uso e desuso", "traps": ["Seleção natural", "Deriva genética", "Fixismo das espécies"], "why": "Lamarck propôs que o uso desenvolve órgãos e que isso seria herdado.", "tier": 4},
    {"title": "Pasteur e o pescoço de cisne", "text": "Refutou a ideia de", "ans": "Geração espontânea", "traps": ["Seleção natural", "Uso e desuso", "Teoria celular"], "why": "Pasteur mostrou que os micróbios vêm do ar e não surgem sozinhos.", "tier": 4}
  ],
  geo: [
    {"title": "Brasil", "text": "Capital", "ans": "Brasília", "traps": ["Rio de Janeiro", "Salvador", "São Paulo"], "why": "Brasília fica no Distrito Federal e é a capital do país desde 1960.", "tier": 1},
    {"title": "São Paulo", "text": "Capital", "ans": "São Paulo", "traps": ["Campinas", "Santos", "Ribeirão Preto"], "why": "A capital paulista tem o mesmo nome do estado e é a maior cidade do Brasil.", "tier": 1},
    {"title": "Rio de Janeiro", "text": "Capital", "ans": "Rio de Janeiro", "traps": ["Niterói", "Petrópolis", "Nova Iguaçu"], "why": "A capital fluminense tem o nome do estado e foi capital do Brasil até 1960.", "tier": 1},
    {"title": "Minas Gerais", "text": "Capital", "ans": "Belo Horizonte", "traps": ["Uberlândia", "Juiz de Fora", "Ouro Preto"], "why": "Belo Horizonte substituiu Ouro Preto como capital mineira em 1897.", "tier": 1},
    {"title": "Bahia", "text": "Capital", "ans": "Salvador", "traps": ["Feira de Santana", "Ilhéus", "Vitória da Conquista"], "why": "Salvador foi a primeira capital do Brasil, de 1549 a 1763.", "tier": 1},
    {"title": "Paraná", "text": "Capital", "ans": "Curitiba", "traps": ["Londrina", "Maringá", "Foz do Iguaçu"], "why": "Curitiba é a capital do Paraná; Foz do Iguaçu é a cidade das cataratas.", "tier": 1},
    {"title": "Rio Grande do Sul", "text": "Capital", "ans": "Porto Alegre", "traps": ["Caxias do Sul", "Pelotas", "Santa Maria"], "why": "Porto Alegre, capital gaúcha, fica às margens do Guaíba.", "tier": 1},
    {"title": "Pernambuco", "text": "Capital", "ans": "Recife", "traps": ["Olinda", "Caruaru", "Petrolina"], "why": "Recife é cortada por rios e cheia de pontes; Olinda é a cidade histórica vizinha.", "tier": 1},
    {"title": "Ceará", "text": "Capital", "ans": "Fortaleza", "traps": ["Juazeiro do Norte", "Sobral", "Caucaia"], "why": "Fortaleza é a capital cearense e uma das maiores cidades do Nordeste.", "tier": 1},
    {"title": "Amazonas", "text": "Capital", "ans": "Manaus", "traps": ["Parintins", "Itacoatiara", "Tabatinga"], "why": "Manaus fica perto do Encontro das Águas dos rios Negro e Solimões.", "tier": 1},
    {"title": "Pará", "text": "Capital", "ans": "Belém", "traps": ["Santarém", "Marabá", "Ananindeua"], "why": "Belém, capital do Pará, é famosa pelo Círio de Nazaré e pelo Ver-o-Peso.", "tier": 1},
    {"title": "Santa Catarina", "text": "Capital", "ans": "Florianópolis", "traps": ["Joinville", "Blumenau", "Chapecó"], "why": "Florianópolis fica em grande parte na Ilha de Santa Catarina.", "tier": 1},
    {"title": "Goiás", "text": "Capital", "ans": "Goiânia", "traps": ["Anápolis", "Aparecida de Goiânia", "Rio Verde"], "why": "Goiânia foi planejada nos anos 1930 e substituiu a Cidade de Goiás.", "tier": 2},
    {"title": "Espírito Santo", "text": "Capital", "ans": "Vitória", "traps": ["Vila Velha", "Serra", "Cariacica"], "why": "Vitória, a capital capixaba, fica em sua maior parte numa ilha.", "tier": 2},
    {"title": "Mato Grosso", "text": "Capital", "ans": "Cuiabá", "traps": ["Campo Grande", "Rondonópolis", "Sinop"], "why": "Cuiabá fica perto do centro geodésico da América do Sul.", "tier": 2},
    {"title": "Mato Grosso do Sul", "text": "Capital", "ans": "Campo Grande", "traps": ["Dourados", "Corumbá", "Cuiabá"], "why": "Mato Grosso do Sul foi criado em 1977; sua capital é Campo Grande.", "tier": 2},
    {"title": "Tocantins", "text": "Capital", "ans": "Palmas", "traps": ["Araguaína", "Gurupi", "Porto Nacional"], "why": "Palmas, fundada em 1989, é a capital mais nova do Brasil.", "tier": 2},
    {"title": "Rondônia", "text": "Capital", "ans": "Porto Velho", "traps": ["Ji-Paraná", "Ariquemes", "Vilhena"], "why": "Porto Velho fica às margens do rio Madeira.", "tier": 2},
    {"title": "Roraima", "text": "Capital", "ans": "Boa Vista", "traps": ["Rorainópolis", "Caracaraí", "Manaus"], "why": "Boa Vista é a única capital brasileira toda ao norte da Linha do Equador.", "tier": 2},
    {"title": "Acre", "text": "Capital", "ans": "Rio Branco", "traps": ["Cruzeiro do Sul", "Sena Madureira", "Porto Velho"], "why": "Rio Branco, capital do Acre, leva o nome do Barão do Rio Branco.", "tier": 2},
    {"title": "Amapá", "text": "Capital", "ans": "Macapá", "traps": ["Santana", "Oiapoque", "Belém"], "why": "Macapá é cortada pela Linha do Equador, marcada pelo monumento Marco Zero.", "tier": 2},
    {"title": "Maranhão", "text": "Capital", "ans": "São Luís", "traps": ["Imperatriz", "Caxias", "Teresina"], "why": "São Luís fica em uma ilha e foi fundada por franceses em 1612.", "tier": 2},
    {"title": "Piauí", "text": "Capital", "ans": "Teresina", "traps": ["Parnaíba", "Picos", "São Luís"], "why": "Teresina é a única capital do Nordeste que não fica no litoral.", "tier": 2},
    {"title": "Rio Grande do Norte", "text": "Capital", "ans": "Natal", "traps": ["Mossoró", "Parnamirim", "João Pessoa"], "why": "Natal, a capital potiguar, abriga o Forte dos Reis Magos, do século XVI.", "tier": 2},
    {"title": "Paraíba", "text": "Capital", "ans": "João Pessoa", "traps": ["Campina Grande", "Patos", "Natal"], "why": "Em João Pessoa fica a Ponta do Seixas, ponto mais a leste do Brasil continental.", "tier": 2},
    {"title": "Alagoas", "text": "Capital", "ans": "Maceió", "traps": ["Arapiraca", "Penedo", "Aracaju"], "why": "Maceió é a capital alagoana; Arapiraca é a segunda maior cidade do estado.", "tier": 2},
    {"title": "Sergipe", "text": "Capital", "ans": "Aracaju", "traps": ["Itabaiana", "Lagarto", "Maceió"], "why": "Aracaju, capital de Sergipe, foi planejada e fundada em 1855.", "tier": 2},
    {"title": "Palmas", "text": "É capital de", "ans": "Tocantins", "traps": ["Goiás", "Maranhão", "Pará"], "why": "Tocantins foi criado em 1988, separado de Goiás; Palmas é sua capital.", "tier": 2},
    {"title": "Porto Velho", "text": "É capital de", "ans": "Rondônia", "traps": ["Acre", "Roraima", "Amazonas"], "why": "Rondônia homenageia o Marechal Rondon; sua capital é Porto Velho.", "tier": 2},
    {"title": "Boa Vista", "text": "É capital de", "ans": "Roraima", "traps": ["Rondônia", "Amapá", "Acre"], "why": "Roraima tem o ponto mais ao norte do Brasil; Boa Vista é sua capital.", "tier": 2},
    {"title": "Macapá", "text": "É capital de", "ans": "Amapá", "traps": ["Pará", "Roraima", "Maranhão"], "why": "Macapá rima com Amapá, e a cidade é cortada pela Linha do Equador.", "tier": 2},
    {"title": "Rio Branco", "text": "É capital de", "ans": "Acre", "traps": ["Rondônia", "Roraima", "Amazonas"], "why": "O Acre passou ao Brasil pelo Tratado de Petrópolis (1903); a capital é Rio Branco.", "tier": 2},
    {"title": "Teresina", "text": "É capital de", "ans": "Piauí", "traps": ["Maranhão", "Ceará", "Tocantins"], "why": "Teresina, capital do Piauí, homenageia a imperatriz Teresa Cristina.", "tier": 2},
    {"title": "Aracaju", "text": "É capital de", "ans": "Sergipe", "traps": ["Alagoas", "Bahia", "Paraíba"], "why": "Sergipe é o menor estado do Brasil; sua capital é Aracaju.", "tier": 2},
    {"title": "Maceió", "text": "É capital de", "ans": "Alagoas", "traps": ["Sergipe", "Pernambuco", "Paraíba"], "why": "Maceió, capital de Alagoas, é famosa por praias e piscinas naturais.", "tier": 2},
    {"title": "João Pessoa", "text": "É capital de", "ans": "Paraíba", "traps": ["Pernambuco", "Rio Grande do Norte", "Alagoas"], "why": "João Pessoa, capital da Paraíba, homenageia um ex-governador do estado.", "tier": 2},
    {"title": "Natal", "text": "É capital de", "ans": "Rio Grande do Norte", "traps": ["Paraíba", "Ceará", "Pernambuco"], "why": "Natal foi fundada em 25 de dezembro de 1599, daí o nome.", "tier": 2},
    {"title": "Cuiabá", "text": "É capital de", "ans": "Mato Grosso", "traps": ["Mato Grosso do Sul", "Goiás", "Rondônia"], "why": "Cuiabá é capital de Mato Grosso; Campo Grande é a de Mato Grosso do Sul.", "tier": 2},
    {"title": "Campo Grande", "text": "É capital de", "ans": "Mato Grosso do Sul", "traps": ["Mato Grosso", "Goiás", "Paraná"], "why": "Campo Grande virou capital quando Mato Grosso do Sul foi criado, em 1977.", "tier": 2},
    {"title": "Tocantins", "text": "Região", "ans": "Norte", "traps": ["Centro-Oeste", "Nordeste", "Sudeste"], "why": "Tocantins saiu de Goiás em 1988, mas faz parte da Região Norte.", "tier": 2},
    {"title": "Maranhão", "text": "Região", "ans": "Nordeste", "traps": ["Norte", "Centro-Oeste", "Sudeste"], "why": "O Maranhão é do Nordeste, embora tenha trechos de floresta amazônica.", "tier": 2},
    {"title": "Bahia", "text": "Região", "ans": "Nordeste", "traps": ["Sudeste", "Centro-Oeste", "Norte"], "why": "A Bahia é o maior estado do Nordeste em área e em população.", "tier": 1},
    {"title": "Mato Grosso do Sul", "text": "Região", "ans": "Centro-Oeste", "traps": ["Sul", "Sudeste", "Norte"], "why": "Mato Grosso do Sul está no Centro-Oeste, apesar do \"Sul\" no nome.", "tier": 1},
    {"title": "Goiás", "text": "Região", "ans": "Centro-Oeste", "traps": ["Sudeste", "Norte", "Nordeste"], "why": "Goiás faz divisa com o Distrito Federal e está no Centro-Oeste.", "tier": 1},
    {"title": "Espírito Santo", "text": "Região", "ans": "Sudeste", "traps": ["Nordeste", "Sul", "Centro-Oeste"], "why": "O Espírito Santo faz divisa com a Bahia, mas pertence ao Sudeste.", "tier": 2},
    {"title": "Minas Gerais", "text": "Região", "ans": "Sudeste", "traps": ["Centro-Oeste", "Nordeste", "Sul"], "why": "Minas Gerais, no Sudeste, é o estado com mais municípios do Brasil.", "tier": 1},
    {"title": "Paraná", "text": "Região", "ans": "Sul", "traps": ["Sudeste", "Centro-Oeste", "Nordeste"], "why": "Paraná, Santa Catarina e Rio Grande do Sul formam a Região Sul.", "tier": 1},
    {"title": "Rondônia", "text": "Região", "ans": "Norte", "traps": ["Centro-Oeste", "Nordeste", "Sudeste"], "why": "Rondônia faz parte da Região Norte e da Amazônia.", "tier": 2},
    {"title": "Piauí", "text": "Região", "ans": "Nordeste", "traps": ["Norte", "Centro-Oeste", "Sudeste"], "why": "O Piauí tem o menor litoral do Nordeste, com cerca de 66 km.", "tier": 2},
    {"title": "Santa Catarina", "text": "Região", "ans": "Sul", "traps": ["Sudeste", "Centro-Oeste", "Norte"], "why": "Santa Catarina fica entre o Paraná e o Rio Grande do Sul.", "tier": 1},
    {"title": "Amapá", "text": "Região", "ans": "Norte", "traps": ["Nordeste", "Centro-Oeste", "Sudeste"], "why": "O Amapá, na Região Norte, faz fronteira com a Guiana Francesa.", "tier": 2},
    {"title": "Argentina", "text": "Capital", "ans": "Buenos Aires", "traps": ["Córdoba", "Rosário", "Mendoza"], "why": "Buenos Aires fica às margens do Rio da Prata.", "tier": 3},
    {"title": "Chile", "text": "Capital", "ans": "Santiago", "traps": ["Concepción", "Antofagasta", "Viña del Mar"], "why": "Santiago fica num vale entre a Cordilheira dos Andes e a da Costa.", "tier": 3},
    {"title": "Uruguai", "text": "Capital", "ans": "Montevidéu", "traps": ["Punta del Este", "Salto", "Paysandú"], "why": "Montevidéu, a capital uruguaia, fica no estuário do Rio da Prata.", "tier": 3},
    {"title": "Paraguai", "text": "Capital", "ans": "Assunção", "traps": ["Ciudad del Este", "Encarnación", "Pedro Juan Caballero"], "why": "Assunção fica às margens do rio Paraguai.", "tier": 3},
    {"title": "Bolívia", "text": "Capital", "ans": "Sucre", "traps": ["Santa Cruz", "Cochabamba", "Potosí"], "why": "Sucre é a capital constitucional; La Paz é a sede do governo boliviano.", "tier": 3},
    {"title": "Peru", "text": "Capital", "ans": "Lima", "traps": ["Trujillo", "Iquitos", "Piura"], "why": "Lima, no litoral do Pacífico, é a capital; Cusco foi a capital do Império Inca.", "tier": 3},
    {"title": "Equador", "text": "Capital", "ans": "Quito", "traps": ["Guayaquil", "Cuenca", "Manta"], "why": "Quito, nos Andes, fica a poucos quilômetros da Linha do Equador.", "tier": 3},
    {"title": "Colômbia", "text": "Capital", "ans": "Bogotá", "traps": ["Medellín", "Cali", "Cartagena"], "why": "Bogotá fica num planalto dos Andes, a cerca de 2.600 m de altitude.", "tier": 3},
    {"title": "Venezuela", "text": "Capital", "ans": "Caracas", "traps": ["Maracaibo", "Valência", "Barquisimeto"], "why": "Caracas, capital venezuelana, é a cidade natal de Simón Bolívar.", "tier": 3},
    {"title": "Guiana", "text": "Capital", "ans": "Georgetown", "traps": ["Paramaribo", "New Amsterdam", "Linden"], "why": "Georgetown tem nome inglês porque a Guiana foi colônia britânica.", "tier": 3},
    {"title": "Suriname", "text": "Capital", "ans": "Paramaribo", "traps": ["Georgetown", "Caiena", "Albina"], "why": "O Suriname foi colônia holandesa; sua capital é Paramaribo.", "tier": 3},
    {"title": "Canadá", "text": "Capital", "ans": "Ottawa", "traps": ["Toronto", "Montreal", "Vancouver"], "why": "Ottawa é a capital; Toronto é só a maior cidade do Canadá.", "tier": 4},
    {"title": "Austrália", "text": "Capital", "ans": "Canberra", "traps": ["Sydney", "Melbourne", "Perth"], "why": "Canberra foi planejada para encerrar a disputa entre Sydney e Melbourne.", "tier": 4},
    {"title": "Turquia", "text": "Capital", "ans": "Ancara", "traps": ["Istambul", "Esmirna", "Antália"], "why": "Ancara virou capital em 1923; Istambul é a maior cidade turca.", "tier": 4},
    {"title": "Suíça", "text": "Capital", "ans": "Berna", "traps": ["Zurique", "Genebra", "Basileia"], "why": "Berna é a \"cidade federal\" e sede do governo; Zurique é a maior cidade.", "tier": 4},
    {"title": "Estados Unidos", "text": "Capital", "ans": "Washington", "traps": ["Nova York", "Chicago", "Los Angeles"], "why": "Washington, D.C., é a capital; Nova York é a maior cidade dos EUA.", "tier": 4},
    {"title": "China", "text": "Capital", "ans": "Pequim", "traps": ["Xangai", "Hong Kong", "Cantão"], "why": "Pequim abriga a Cidade Proibida; Xangai é o grande centro financeiro.", "tier": 4},
    {"title": "Japão", "text": "Capital", "ans": "Tóquio", "traps": ["Osaka", "Quioto", "Hiroshima"], "why": "Tóquio é a capital desde 1868; antes, a capital imperial era Quioto.", "tier": 4},
    {"title": "Índia", "text": "Capital", "ans": "Nova Délhi", "traps": ["Mumbai", "Calcutá", "Bangalore"], "why": "Nova Délhi é a capital; Mumbai é o maior centro financeiro da Índia.", "tier": 4},
    {"title": "Egito", "text": "Capital", "ans": "Cairo", "traps": ["Alexandria", "Gizé", "Luxor"], "why": "O Cairo fica às margens do rio Nilo, perto das pirâmides de Gizé.", "tier": 4},
    {"title": "Nigéria", "text": "Capital", "ans": "Abuja", "traps": ["Lagos", "Kano", "Ibadan"], "why": "Abuja substituiu Lagos como capital da Nigéria em 1991.", "tier": 4},
    {"title": "Marrocos", "text": "Capital", "ans": "Rabat", "traps": ["Casablanca", "Marrakech", "Fez"], "why": "Rabat é a capital; Casablanca é a maior cidade do Marrocos.", "tier": 4},
    {"title": "Nova Zelândia", "text": "Capital", "ans": "Wellington", "traps": ["Auckland", "Christchurch", "Queenstown"], "why": "Wellington é a capital; Auckland é a maior cidade neozelandesa.", "tier": 4},
    {"title": "Rússia", "text": "Capital", "ans": "Moscou", "traps": ["São Petersburgo", "Novosibirsk", "Kazan"], "why": "São Petersburgo foi capital até 1918, quando Moscou reassumiu o posto.", "tier": 4},
    {"title": "Alemanha", "text": "Capital", "ans": "Berlim", "traps": ["Munique", "Frankfurt", "Hamburgo"], "why": "Berlim voltou a ser a capital após a reunificação alemã, em 1990.", "tier": 4},
    {"title": "Vietnã", "text": "Capital", "ans": "Hanói", "traps": ["Ho Chi Minh", "Da Nang", "Hue"], "why": "Hanói fica no norte; a antiga Saigon, no sul, é a maior cidade.", "tier": 4},
    {"title": "Maior bioma do Brasil", "text": "Bioma", "ans": "Amazônia", "traps": ["Cerrado", "Mata Atlântica", "Caatinga"], "why": "A Amazônia ocupa cerca de 49% do território brasileiro.", "tier": 1},
    {"title": "Exclusivamente brasileiro", "text": "Bioma", "ans": "Caatinga", "traps": ["Amazônia", "Pantanal", "Pampa"], "why": "A Caatinga é o único bioma que existe apenas no Brasil.", "tier": 2},
    {"title": "Maior planície alagável do mundo", "text": "Bioma", "ans": "Pantanal", "traps": ["Pampa", "Cerrado", "Caatinga"], "why": "No Brasil, o Pantanal fica em MT e MS e alaga na estação das chuvas.", "tier": 1},
    {"title": "Campos do Rio Grande do Sul", "text": "Bioma", "ans": "Pampa", "traps": ["Cerrado", "Pantanal", "Caatinga"], "why": "No Brasil, o Pampa, de campos baixos, só aparece no Rio Grande do Sul.", "tier": 2},
    {"title": "Savana do Brasil Central", "text": "Bioma", "ans": "Cerrado", "traps": ["Caatinga", "Pampa", "Pantanal"], "why": "O Cerrado é a savana mais biodiversa do mundo e o 2º maior bioma do país.", "tier": 2},
    {"title": "Pau-brasil e mico-leão-dourado", "text": "Bioma", "ans": "Mata Atlântica", "traps": ["Amazônia", "Cerrado", "Caatinga"], "why": "A Mata Atlântica cobria boa parte do leste do país; hoje restam cerca de 12% dela.", "tier": 1},
    {"title": "Rio São Francisco", "text": "Nasce em", "ans": "Minas Gerais", "traps": ["Bahia", "Goiás", "Pernambuco"], "why": "O Velho Chico nasce na Serra da Canastra (MG) e deságua entre AL e SE.", "tier": 2},
    {"title": "Ponto mais alto do Brasil", "text": "Nome", "ans": "Pico da Neblina", "traps": ["Pico da Bandeira", "Monte Roraima", "Pico Paraná"], "why": "O Pico da Neblina, no Amazonas, tem cerca de 2.995 m de altitude.", "tier": 3},
    {"title": "Rio com mais água do mundo", "text": "Rio", "ans": "Amazonas", "traps": ["Nilo", "Paraná", "São Francisco"], "why": "O Amazonas despeja no mar mais água que qualquer outro rio do planeta.", "tier": 1},
    {"title": "Usina de Itaipu", "text": "Rio", "ans": "Paraná", "traps": ["São Francisco", "Tocantins", "Iguaçu"], "why": "Itaipu, no rio Paraná, é uma usina binacional do Brasil com o Paraguai.", "tier": 2},
    {"title": "Encontro das Águas (Manaus)", "text": "Rios", "ans": "Negro e Solimões", "traps": ["Madeira e Purus", "Xingu e Tapajós", "Tocantins e Araguaia"], "why": "Em Manaus, o rio Negro escuro e o Solimões barrento correm lado a lado.", "tier": 2}
  ],
  };
})();
