// Corrida Quanta — bancos de perguntas de Química e Física (dados; a lógica fica em js/modes.js).
// Notação rica: _x / _{xy} = índice, ^x / ^{xy} = expoente (H_2O, C_6H_{12}O_6, m·v^2/2).
// elements:  { name, symbol, z, mass, tier: facil|medio|dificil, traps: [3 símbolos errados], why }
// molecules: { name, formula, cls: acido|base|sal|oxido|organico|simples|outro, tier, traps: [3 fórmulas erradas], why }
// physics:   { name, lhs, rhs, tier: 1..4, traps: [3 equações erradas], why, unit, unit_traps: [3 unidades erradas] }
// "why" é a frase mostrada depois do erro. Revisão: Samuel (professor).
(() => {
  'use strict';
  window.QC = window.QC || {};
  QC.Banks = {
  elements: [
    {"name": "Hidrogênio", "symbol": "H", "z": 1, "mass": 1, "tier": "facil", "traps": ["Hi", "Hd", "Hg"], "why": "Hidrogênio é H, o mais leve de todos, número atômico 1."},
    {"name": "Hélio", "symbol": "He", "z": 2, "mass": 4, "tier": "facil", "traps": ["H", "Hl", "Hi"], "why": "Hélio é He: duas letras, gás nobre mais leve."},
    {"name": "Lítio", "symbol": "Li", "z": 3, "mass": 7, "tier": "facil", "traps": ["L", "Lt", "Lu"], "why": "Lítio é Li, o metal mais leve que existe."},
    {"name": "Berílio", "symbol": "Be", "z": 4, "mass": 9, "tier": "facil", "traps": ["B", "Br", "Bl"], "why": "Berílio é Be; B sozinho é o boro."},
    {"name": "Boro", "symbol": "B", "z": 5, "mass": 11, "tier": "facil", "traps": ["Bo", "Br", "Bh"], "why": "Boro é só B, uma letra, número atômico 5."},
    {"name": "Carbono", "symbol": "C", "z": 6, "mass": 12, "tier": "facil", "traps": ["Ca", "Cb", "Co"], "why": "Carbono é só C; Ca é cálcio e Co é cobalto."},
    {"name": "Nitrogênio", "symbol": "N", "z": 7, "mass": 14, "tier": "facil", "traps": ["Ni", "Nt", "Na"], "why": "Nitrogênio é só N; Na é sódio e Ni é níquel."},
    {"name": "Oxigênio", "symbol": "O", "z": 8, "mass": 16, "tier": "facil", "traps": ["Ox", "Os", "Og"], "why": "Oxigênio é só O, o elemento mais abundante na crosta."},
    {"name": "Flúor", "symbol": "F", "z": 9, "mass": 19, "tier": "facil", "traps": ["Fl", "Fe", "Fu"], "why": "Flúor é só F; Fe é ferro e Fl é fleróvio."},
    {"name": "Neônio", "symbol": "Ne", "z": 10, "mass": 20, "tier": "facil", "traps": ["N", "No", "Nn"], "why": "Neônio é Ne, gás nobre das luzes de letreiro."},
    {"name": "Sódio", "symbol": "Na", "z": 11, "mass": 23, "tier": "facil", "traps": ["So", "S", "Sd"], "why": "Sódio é Na, do latim natrium."},
    {"name": "Magnésio", "symbol": "Mg", "z": 12, "mass": 24, "tier": "facil", "traps": ["Ma", "Mn", "M"], "why": "Magnésio é Mg; Mn é manganês."},
    {"name": "Alumínio", "symbol": "Al", "z": 13, "mass": 27, "tier": "facil", "traps": ["A", "Am", "Au"], "why": "Alumínio é Al; Au é ouro, Am é amerício."},
    {"name": "Silício", "symbol": "Si", "z": 14, "mass": 28, "tier": "facil", "traps": ["S", "Sl", "Sc"], "why": "Silício é Si; S sozinho é enxofre."},
    {"name": "Fósforo", "symbol": "P", "z": 15, "mass": 31, "tier": "facil", "traps": ["F", "Fo", "Ph"], "why": "Fósforo é P, de phosphorus; F é flúor."},
    {"name": "Enxofre", "symbol": "S", "z": 16, "mass": 32, "tier": "facil", "traps": ["En", "Ex", "Su"], "why": "Enxofre é S, de sulphur em latim."},
    {"name": "Cloro", "symbol": "Cl", "z": 17, "mass": 35.5, "tier": "facil", "traps": ["C", "Co", "Cr"], "why": "Cloro é Cl; Co é cobalto e Cr é cromo."},
    {"name": "Argônio", "symbol": "Ar", "z": 18, "mass": 40, "tier": "facil", "traps": ["A", "Ag", "An"], "why": "Argônio é Ar, gás nobre; Ag é prata."},
    {"name": "Cálcio", "symbol": "Ca", "z": 20, "mass": 40, "tier": "facil", "traps": ["C", "Cl", "Cc"], "why": "Cálcio é Ca; C sozinho é carbono."},
    {"name": "Ferro", "symbol": "Fe", "z": 26, "mass": 56, "tier": "facil", "traps": ["F", "Fr", "Ir"], "why": "Ferro é Fe, do latim ferrum; F é flúor."},
    {"name": "Zinco", "symbol": "Zn", "z": 30, "mass": 65, "tier": "facil", "traps": ["Z", "Zi", "Zc"], "why": "Zinco é Zn, número atômico 30."},
    {"name": "Iodo", "symbol": "I", "z": 53, "mass": 127, "tier": "facil", "traps": ["Io", "Id", "In"], "why": "Iodo é só I; In é índio."},
    {"name": "Potássio", "symbol": "K", "z": 19, "mass": 39, "tier": "medio", "traps": ["P", "Po", "Pt"], "why": "Potássio é K, do latim kalium."},
    {"name": "Cobre", "symbol": "Cu", "z": 29, "mass": 63.5, "tier": "medio", "traps": ["Co", "Cb", "Cr"], "why": "Cobre é Cu, do latim cuprum; Co é cobalto."},
    {"name": "Prata", "symbol": "Ag", "z": 47, "mass": 108, "tier": "medio", "traps": ["Pr", "Pt", "Pa"], "why": "Prata é Ag, do latim argentum."},
    {"name": "Ouro", "symbol": "Au", "z": 79, "mass": 197, "tier": "medio", "traps": ["O", "Ou", "Ag"], "why": "Ouro é Au, do latim aurum; Ag é prata."},
    {"name": "Chumbo", "symbol": "Pb", "z": 82, "mass": 207, "tier": "medio", "traps": ["Ch", "Cb", "Cu"], "why": "Chumbo é Pb, do latim plumbum."},
    {"name": "Mercúrio", "symbol": "Hg", "z": 80, "mass": 201, "tier": "medio", "traps": ["Me", "Mc", "Mr"], "why": "Mercúrio é Hg, de hydrargyrum, 'prata líquida'."},
    {"name": "Estanho", "symbol": "Sn", "z": 50, "mass": 119, "tier": "medio", "traps": ["Es", "Et", "St"], "why": "Estanho é Sn, do latim stannum."},
    {"name": "Manganês", "symbol": "Mn", "z": 25, "mass": 55, "tier": "medio", "traps": ["Mg", "Ma", "Mm"], "why": "Manganês é Mn; Mg é magnésio."},
    {"name": "Níquel", "symbol": "Ni", "z": 28, "mass": 59, "tier": "medio", "traps": ["N", "Nq", "Nk"], "why": "Níquel é Ni; N sozinho é nitrogênio."},
    {"name": "Cobalto", "symbol": "Co", "z": 27, "mass": 59, "tier": "medio", "traps": ["Cb", "Cu", "Ct"], "why": "Cobalto é Co; Cu é cobre."},
    {"name": "Cromo", "symbol": "Cr", "z": 24, "mass": 52, "tier": "medio", "traps": ["Cm", "Co", "Ch"], "why": "Cromo é Cr; Cm é cúrio."},
    {"name": "Bromo", "symbol": "Br", "z": 35, "mass": 80, "tier": "medio", "traps": ["B", "Bo", "Bm"], "why": "Bromo é Br, único não metal líquido; B é boro."},
    {"name": "Bário", "symbol": "Ba", "z": 56, "mass": 137, "tier": "medio", "traps": ["B", "Br", "Bi"], "why": "Bário é Ba; Bi é bismuto."},
    {"name": "Urânio", "symbol": "U", "z": 92, "mass": 238, "tier": "medio", "traps": ["Ur", "Un", "Ua"], "why": "Urânio é só U, número atômico 92."},
    {"name": "Platina", "symbol": "Pt", "z": 78, "mass": 195, "tier": "medio", "traps": ["Pl", "Pa", "P"], "why": "Platina é Pt; P é fósforo, Pa é protactínio."},
    {"name": "Tungstênio", "symbol": "W", "z": 74, "mass": 184, "tier": "medio", "traps": ["Tu", "Tg", "Tn"], "why": "Tungstênio é W, de wolfrâmio, o nome alemão."},
    {"name": "Antimônio", "symbol": "Sb", "z": 51, "mass": 122, "tier": "medio", "traps": ["An", "At", "Am"], "why": "Antimônio é Sb, do latim stibium."},
    {"name": "Titânio", "symbol": "Ti", "z": 22, "mass": 48, "tier": "medio", "traps": ["T", "Tt", "Tn"], "why": "Titânio é Ti, número atômico 22."},
    {"name": "Criptônio", "symbol": "Kr", "z": 36, "mass": 84, "tier": "medio", "traps": ["Cr", "Cp", "K"], "why": "Criptônio é Kr; Cr é cromo, K é potássio."},
    {"name": "Xenônio", "symbol": "Xe", "z": 54, "mass": 131, "tier": "medio", "traps": ["X", "Xn", "Xo"], "why": "Xenônio é Xe, gás nobre pesado, número 54."},
    {"name": "Radônio", "symbol": "Rn", "z": 86, "mass": 222, "tier": "medio", "traps": ["Ra", "Rd", "Ro"], "why": "Radônio é Rn; Ra é rádio."},
    {"name": "Estrôncio", "symbol": "Sr", "z": 38, "mass": 88, "tier": "medio", "traps": ["Es", "St", "Sn"], "why": "Estrôncio é Sr; Sn é estanho."},
    {"name": "Rubídio", "symbol": "Rb", "z": 37, "mass": 85, "tier": "dificil", "traps": ["Ru", "R", "Rd"], "why": "Rubídio é Rb; Ru é rutênio."},
    {"name": "Césio", "symbol": "Cs", "z": 55, "mass": 133, "tier": "dificil", "traps": ["Ce", "C", "Ci"], "why": "Césio é Cs; Ce é cério."},
    {"name": "Germânio", "symbol": "Ge", "z": 32, "mass": 73, "tier": "dificil", "traps": ["Gm", "Gr", "G"], "why": "Germânio é Ge, semicondutor, número atômico 32."},
    {"name": "Arsênio", "symbol": "As", "z": 33, "mass": 75, "tier": "dificil", "traps": ["Ar", "Ac", "A"], "why": "Arsênio é As; Ar é argônio."},
    {"name": "Selênio", "symbol": "Se", "z": 34, "mass": 79, "tier": "dificil", "traps": ["S", "Sl", "Si"], "why": "Selênio é Se; S é enxofre e Si é silício."},
    {"name": "Telúrio", "symbol": "Te", "z": 52, "mass": 128, "tier": "dificil", "traps": ["Tl", "Tu", "T"], "why": "Telúrio é Te; Tl é tálio."},
    {"name": "Bismuto", "symbol": "Bi", "z": 83, "mass": 209, "tier": "dificil", "traps": ["Bs", "B", "Bm"], "why": "Bismuto é Bi, número atômico 83."},
    {"name": "Polônio", "symbol": "Po", "z": 84, "mass": 209, "tier": "dificil", "traps": ["P", "Pl", "Pn"], "why": "Polônio é Po, descoberto por Marie Curie."},
    {"name": "Cádmio", "symbol": "Cd", "z": 48, "mass": 112, "tier": "dificil", "traps": ["Ca", "Cm", "Cc"], "why": "Cádmio é Cd; Ca é cálcio."},
    {"name": "Índio", "symbol": "In", "z": 49, "mass": 115, "tier": "dificil", "traps": ["I", "Id", "Ii"], "why": "Índio é In; I sozinho é iodo."},
    {"name": "Gálio", "symbol": "Ga", "z": 31, "mass": 70, "tier": "dificil", "traps": ["G", "Gl", "Ge"], "why": "Gálio é Ga, metal que derrete na mão; Ge é germânio."},
    {"name": "Escândio", "symbol": "Sc", "z": 21, "mass": 45, "tier": "dificil", "traps": ["Es", "Ec", "Si"], "why": "Escândio é Sc, de Escandinávia."},
    {"name": "Vanádio", "symbol": "V", "z": 23, "mass": 51, "tier": "dificil", "traps": ["Va", "Vn", "Vd"], "why": "Vanádio é só V, número atômico 23."},
    {"name": "Molibdênio", "symbol": "Mo", "z": 42, "mass": 96, "tier": "dificil", "traps": ["Mb", "Ml", "M"], "why": "Molibdênio é Mo, número atômico 42."},
    {"name": "Paládio", "symbol": "Pd", "z": 46, "mass": 106, "tier": "dificil", "traps": ["Pa", "Pl", "P"], "why": "Paládio é Pd; Pa é protactínio."},
    {"name": "Irídio", "symbol": "Ir", "z": 77, "mass": 192, "tier": "dificil", "traps": ["I", "Id", "In"], "why": "Irídio é Ir; I é iodo e In é índio."},
    {"name": "Ósmio", "symbol": "Os", "z": 76, "mass": 190, "tier": "dificil", "traps": ["O", "Om", "Oi"], "why": "Ósmio é Os, o metal mais denso."},
    {"name": "Tálio", "symbol": "Tl", "z": 81, "mass": 204, "tier": "dificil", "traps": ["Ta", "T", "Th"], "why": "Tálio é Tl; Ta é tântalo e Th é tório."},
    {"name": "Rádio", "symbol": "Ra", "z": 88, "mass": 226, "tier": "dificil", "traps": ["Rd", "R", "Rn"], "why": "Rádio é Ra; Rn é radônio."},
    {"name": "Tório", "symbol": "Th", "z": 90, "mass": 232, "tier": "dificil", "traps": ["To", "T", "Tr"], "why": "Tório é Th, de Thor, deus nórdico."}
  ],
  molecules: [
    {"name": "Água", "formula": "H_2O", "cls": "outro", "tier": "facil", "traps": ["H_2O_2", "HO_2", "H_3O"], "why": "Água: 2 hidrogênios e 1 oxigênio, H₂O."},
    {"name": "Gás carbônico", "formula": "CO_2", "cls": "oxido", "tier": "facil", "traps": ["CO", "C_2O", "CO_3"], "why": "Gás carbônico tem 2 oxigênios, CO₂; CO é o monóxido."},
    {"name": "Monóxido de carbono", "formula": "CO", "cls": "oxido", "tier": "facil", "traps": ["CO_2", "C_2O", "CO_3"], "why": "Monóxido = 1 oxigênio: CO, gás tóxico da combustão incompleta."},
    {"name": "Gás oxigênio", "formula": "O_2", "cls": "simples", "tier": "facil", "traps": ["O", "O_3", "H_2O"], "why": "Gás oxigênio é diatômico: O₂; O₃ é o ozônio."},
    {"name": "Ozônio", "formula": "O_3", "cls": "simples", "tier": "facil", "traps": ["O_2", "O", "O_4"], "why": "Ozônio tem 3 átomos de oxigênio: O₃."},
    {"name": "Gás hidrogênio", "formula": "H_2", "cls": "simples", "tier": "facil", "traps": ["H", "H_3", "H_2O"], "why": "Hidrogênio gasoso é diatômico: H₂."},
    {"name": "Gás nitrogênio", "formula": "N_2", "cls": "simples", "tier": "facil", "traps": ["N", "N_3", "NH_3"], "why": "Nitrogênio do ar é N₂, molécula diatômica com ligação tripla."},
    {"name": "Amônia", "formula": "NH_3", "cls": "outro", "tier": "facil", "traps": ["NH_4", "NH_2", "NH"], "why": "Amônia: 1 nitrogênio e 3 hidrogênios, NH₃; NH₄⁺ é o íon amônio."},
    {"name": "Metano", "formula": "CH_4", "cls": "organico", "tier": "facil", "traps": ["CH_3", "C_2H_6", "CH_2"], "why": "Metano é o alcano mais simples: 1 carbono e 4 hidrogênios, CH₄."},
    {"name": "Cloreto de sódio (sal de cozinha)", "formula": "NaCl", "cls": "sal", "tier": "facil", "traps": ["NaCl_2", "Na_2Cl", "NaClO"], "why": "Sal de cozinha: Na⁺ e Cl⁻ na proporção 1:1, NaCl."},
    {"name": "Água oxigenada", "formula": "H_2O_2", "cls": "outro", "tier": "facil", "traps": ["H_2O", "HO_2", "H_2O_3"], "why": "Água oxigenada tem um oxigênio a mais que a água: H₂O₂."},
    {"name": "Ácido clorídrico", "formula": "HCl", "cls": "acido", "tier": "facil", "traps": ["HCl_2", "H_2Cl", "HClO"], "why": "Ácido clorídrico: HCl, hidrogênio e cloro na proporção 1:1."},
    {"name": "Soda cáustica (hidróxido de sódio)", "formula": "NaOH", "cls": "base", "tier": "facil", "traps": ["Na(OH)_2", "Na_2OH", "NaO"], "why": "Hidróxido de sódio: Na⁺ e OH⁻, NaOH."},
    {"name": "Gás cloro", "formula": "Cl_2", "cls": "simples", "tier": "facil", "traps": ["Cl", "Cl_3", "HCl"], "why": "Cloro gasoso é diatômico: Cl₂."},
    {"name": "Cloreto de potássio", "formula": "KCl", "cls": "sal", "tier": "facil", "traps": ["KCl_2", "K_2Cl", "KClO_3"], "why": "Cloreto de potássio: K⁺ e Cl⁻ na proporção 1:1, KCl."},
    {"name": "Óxido de magnésio", "formula": "MgO", "cls": "oxido", "tier": "facil", "traps": ["MgO_2", "Mg_2O", "Mg(OH)_2"], "why": "Magnésio é +2 e oxigênio é −2: MgO."},
    {"name": "Cal virgem (óxido de cálcio)", "formula": "CaO", "cls": "oxido", "tier": "facil", "traps": ["CaO_2", "Ca_2O", "Ca(OH)_2"], "why": "Cal virgem é CaO; Ca(OH)₂ é a cal hidratada."},
    {"name": "Dióxido de enxofre", "formula": "SO_2", "cls": "oxido", "tier": "facil", "traps": ["SO_3", "SO", "S_2O"], "why": "Dióxido = 2 oxigênios: SO₂; SO₃ é o trióxido."},
    {"name": "Dióxido de nitrogênio", "formula": "NO_2", "cls": "oxido", "tier": "facil", "traps": ["NO", "N_2O", "NO_3"], "why": "Dióxido de nitrogênio: NO₂, gás castanho da poluição."},
    {"name": "Óxido nitroso (gás hilariante)", "formula": "N_2O", "cls": "oxido", "tier": "facil", "traps": ["NO", "NO_2", "N_2O_3"], "why": "Gás hilariante: 2 nitrogênios e 1 oxigênio, N₂O."},
    {"name": "Ácido sulfúrico", "formula": "H_2SO_4", "cls": "acido", "tier": "medio", "traps": ["H_2SO_3", "H_2S", "HSO_4"], "why": "Ácido sulfúrico tem 4 oxigênios; H₂SO₃ é o sulfuroso."},
    {"name": "Ácido nítrico", "formula": "HNO_3", "cls": "acido", "tier": "medio", "traps": ["HNO_2", "H_2NO_3", "HNO_4"], "why": "Ácido nítrico tem 3 oxigênios: HNO₃; HNO₂ é o nitroso."},
    {"name": "Ácido fosfórico", "formula": "H_3PO_4", "cls": "acido", "tier": "medio", "traps": ["H_2PO_4", "H_3PO_3", "HPO_4"], "why": "Ácido fosfórico tem 3 H e 4 O: H₃PO₄."},
    {"name": "Ácido carbônico", "formula": "H_2CO_3", "cls": "acido", "tier": "medio", "traps": ["HCO_3", "H_2CO_2", "H_2CO_4"], "why": "Ácido carbônico = CO₂ + H₂O: H₂CO₃."},
    {"name": "Carbonato de cálcio", "formula": "CaCO_3", "cls": "sal", "tier": "medio", "traps": ["CaCO_2", "Ca_2CO_3", "CaCO_4"], "why": "Carbonato é CO₃²⁻ e cálcio é +2: CaCO₃, o calcário."},
    {"name": "Bicarbonato de sódio", "formula": "NaHCO_3", "cls": "sal", "tier": "medio", "traps": ["Na_2CO_3", "NaCO_3", "NaHCO_2"], "why": "Bicarbonato tem H: NaHCO₃; carbonato de sódio é Na₂CO₃."},
    {"name": "Hidróxido de cálcio (cal hidratada)", "formula": "Ca(OH)_2", "cls": "base", "tier": "medio", "traps": ["CaOH", "Ca_2OH", "Ca(OH)_3"], "why": "Cálcio é +2, precisa de 2 OH⁻: Ca(OH)₂."},
    {"name": "Cloreto de cálcio", "formula": "CaCl_2", "cls": "sal", "tier": "medio", "traps": ["CaCl", "Ca_2Cl", "CaCl_3"], "why": "Cálcio +2 e cloro −1: CaCl₂."},
    {"name": "Sulfato de cobre II", "formula": "CuSO_4", "cls": "sal", "tier": "medio", "traps": ["CuSO_3", "Cu_2SO_4", "CuS"], "why": "Sulfato é SO₄²⁻ e cobre II é +2: CuSO₄, sal azul; Cu₂SO₄ seria o de cobre I."},
    {"name": "Óxido de ferro III (ferrugem)", "formula": "Fe_2O_3", "cls": "oxido", "tier": "medio", "traps": ["FeO", "Fe_3O_2", "FeO_3"], "why": "Ferro +3 e oxigênio −2 cruzam os índices: Fe₂O₃."},
    {"name": "Óxido de alumínio (alumina)", "formula": "Al_2O_3", "cls": "oxido", "tier": "medio", "traps": ["AlO", "Al_3O_2", "AlO_3"], "why": "Alumínio +3 e oxigênio −2: Al₂O₃."},
    {"name": "Hidróxido de potássio", "formula": "KOH", "cls": "base", "tier": "medio", "traps": ["K(OH)_2", "K_2OH", "KO"], "why": "Potássio é +1, um só OH⁻: KOH."},
    {"name": "Hidróxido de magnésio (leite de magnésia)", "formula": "Mg(OH)_2", "cls": "base", "tier": "medio", "traps": ["MgOH", "Mg_2OH", "Mg(OH)_3"], "why": "Magnésio +2 pede 2 OH⁻: Mg(OH)₂."},
    {"name": "Nitrato de sódio", "formula": "NaNO_3", "cls": "sal", "tier": "medio", "traps": ["NaNO_2", "Na_2NO_3", "NaNO_4"], "why": "Nitrato é NO₃⁻: NaNO₃; NaNO₂ é o nitrito."},
    {"name": "Nitrato de potássio (salitre)", "formula": "KNO_3", "cls": "sal", "tier": "medio", "traps": ["KNO_2", "K_2NO_3", "KNO_4"], "why": "Salitre: K⁺ e NO₃⁻, KNO₃."},
    {"name": "Carbonato de sódio (barrilha)", "formula": "Na_2CO_3", "cls": "sal", "tier": "medio", "traps": ["NaCO_3", "NaHCO_3", "Na_2CO_2"], "why": "Carbonato é CO₃²⁻, precisa de 2 Na⁺: Na₂CO₃."},
    {"name": "Sulfato de potássio", "formula": "K_2SO_4", "cls": "sal", "tier": "medio", "traps": ["KSO_4", "K_2SO_3", "K_2S"], "why": "Sulfato SO₄²⁻ com 2 K⁺: K₂SO₄."},
    {"name": "Ácido fluorídrico", "formula": "HF", "cls": "acido", "tier": "medio", "traps": ["HF_2", "H_2F", "HFO"], "why": "Ácido fluorídrico: HF, ataca até o vidro."},
    {"name": "Ácido bromídrico", "formula": "HBr", "cls": "acido", "tier": "medio", "traps": ["HBr_2", "H_2Br", "HBrO"], "why": "Ácido bromídrico: HBr, hidrácido como o HCl."},
    {"name": "Gás sulfídrico (ácido sulfídrico)", "formula": "H_2S", "cls": "acido", "tier": "medio", "traps": ["HS", "HS_2", "H_2SO_3"], "why": "Sulfídrico: enxofre −2 com 2 H, H₂S, cheiro de ovo podre."},
    {"name": "Trióxido de enxofre", "formula": "SO_3", "cls": "oxido", "tier": "medio", "traps": ["SO_2", "S_2O_3", "SO_4"], "why": "Trióxido = 3 oxigênios: SO₃; com água forma H₂SO₄."},
    {"name": "Dióxido de silício (sílica)", "formula": "SiO_2", "cls": "oxido", "tier": "medio", "traps": ["SiO", "Si_2O", "SiO_3"], "why": "Sílica, principal componente da areia: SiO₂, análoga ao CO₂ do mesmo grupo."},
    {"name": "Óxido de zinco", "formula": "ZnO", "cls": "oxido", "tier": "medio", "traps": ["ZnO_2", "Zn_2O", "Zn(OH)_2"], "why": "Zinco +2 e oxigênio −2: ZnO."},
    {"name": "Dióxido de chumbo", "formula": "PbO_2", "cls": "oxido", "tier": "medio", "traps": ["PbO", "Pb_2O", "PbO_3"], "why": "Chumbo IV com 2 oxigênios: PbO₂, da bateria de carro."},
    {"name": "Glicose", "formula": "C_6H_{12}O_6", "cls": "organico", "tier": "dificil", "traps": ["C_6H_6O_6", "C_{12}H_{22}O_{11}", "C_6H_{10}O_5"], "why": "Glicose: 6 C, 12 H e 6 O; sacarose é C₁₂H₂₂O₁₁."},
    {"name": "Sacarose", "formula": "C_{12}H_{22}O_{11}", "cls": "organico", "tier": "dificil", "traps": ["C_6H_{12}O_6", "C_{12}H_{24}O_{12}", "C_{12}H_{22}O_{12}"], "why": "Sacarose = 2 açúcares menos uma água: C₁₂H₂₂O₁₁."},
    {"name": "Etanol", "formula": "C_2H_5OH", "cls": "organico", "tier": "dificil", "traps": ["CH_3OH", "C_3H_7OH", "C_2H_5O"], "why": "Etanol tem 2 carbonos: C₂H₅OH; CH₃OH é o metanol."},
    {"name": "Metanol", "formula": "CH_3OH", "cls": "organico", "tier": "dificil", "traps": ["C_2H_5OH", "CH_4O_2", "CH_2OH"], "why": "Metanol tem 1 carbono: CH₃OH, álcool tóxico."},
    {"name": "Ácido acético (vinagre)", "formula": "CH_3COOH", "cls": "organico", "tier": "dificil", "traps": ["HCOOH", "CH_3CHO", "C_2H_5OH"], "why": "Ácido acético: 2 carbonos com grupo COOH, CH₃COOH."},
    {"name": "Propano", "formula": "C_3H_8", "cls": "organico", "tier": "dificil", "traps": ["C_3H_6", "C_4H_{10}", "C_2H_6"], "why": "Alcano com 3 carbonos: 2·3+2 = 8 hidrogênios, C₃H₈."},
    {"name": "Butano", "formula": "C_4H_{10}", "cls": "organico", "tier": "dificil", "traps": ["C_4H_8", "C_3H_8", "C_4H_{12}"], "why": "Butano: 4 carbonos e 2·4+2 = 10 hidrogênios, C₄H₁₀."},
    {"name": "Etileno (eteno)", "formula": "C_2H_4", "cls": "organico", "tier": "dificil", "traps": ["C_2H_6", "C_2H_2", "CH_4"], "why": "Eteno tem ligação dupla: C₂H₄; etano é C₂H₆."},
    {"name": "Acetileno (etino)", "formula": "C_2H_2", "cls": "organico", "tier": "dificil", "traps": ["C_2H_4", "C_2H_6", "CH_2"], "why": "Acetileno tem ligação tripla: C₂H₂, gás da solda."},
    {"name": "Benzeno", "formula": "C_6H_6", "cls": "organico", "tier": "dificil", "traps": ["C_6H_{12}", "C_6H_{14}", "C_6H_5"], "why": "Benzeno: anel de 6 carbonos com 6 hidrogênios, C₆H₆."},
    {"name": "Ureia", "formula": "(NH_2)_2CO", "cls": "organico", "tier": "dificil", "traps": ["(NH_4)_2CO_3", "NH_2COOH", "NH_2CO"], "why": "Ureia: dois grupos NH₂ ligados a um C=O, (NH₂)₂CO."},
    {"name": "Ácido cítrico", "formula": "C_6H_8O_7", "cls": "organico", "tier": "dificil", "traps": ["C_6H_{12}O_6", "C_6H_8O_6", "C_6H_{10}O_7"], "why": "Ácido cítrico: C₆H₈O₇; C₆H₈O₆ é a vitamina C."},
    {"name": "Cafeína", "formula": "C_8H_{10}N_4O_2", "cls": "organico", "tier": "dificil", "traps": ["C_8H_{10}N_2O_4", "C_7H_8N_4O_2", "C_8H_{12}N_4O_2"], "why": "Cafeína: C₈H₁₀N₄O₂, com 4 nitrogênios."},
    {"name": "Ácido lático", "formula": "C_3H_6O_3", "cls": "organico", "tier": "dificil", "traps": ["C_3H_8O_3", "C_2H_4O_2", "C_3H_6O_2"], "why": "Ácido lático (formado no músculo em esforço intenso): C₃H₆O₃."},
    {"name": "Glicerol (glicerina)", "formula": "C_3H_8O_3", "cls": "organico", "tier": "dificil", "traps": ["C_3H_6O_3", "C_3H_8O", "C_2H_6O_2"], "why": "Glicerol: 3 carbonos e 3 hidroxilas, C₃H₈O₃."},
    {"name": "Acetona", "formula": "C_3H_6O", "cls": "organico", "tier": "dificil", "traps": ["C_3H_8O", "C_2H_4O", "C_3H_6O_2"], "why": "Acetona (propanona): C₃H₆O, cetona de 3 carbonos."},
    {"name": "Ácido fórmico", "formula": "HCOOH", "cls": "organico", "tier": "dificil", "traps": ["CH_3COOH", "HCHO", "CH_3OH"], "why": "Ácido fórmico, o ácido carboxílico mais simples: HCOOH, da formiga."},
    {"name": "Íon amônio", "formula": "NH_4^+", "cls": "outro", "tier": "dificil", "traps": ["NH_3", "NH_4", "NH_3^+"], "why": "Amônio: NH₃ + H⁺ = NH₄⁺, com carga positiva."},
    {"name": "Sulfato de amônio", "formula": "(NH_4)_2SO_4", "cls": "sal", "tier": "dificil", "traps": ["NH_4SO_4", "(NH_4)_2SO_3", "(NH_3)_2SO_4"], "why": "Amônio NH₄⁺ é +1 e sulfato é −2: (NH₄)₂SO₄."},
    {"name": "Permanganato de potássio", "formula": "KMnO_4", "cls": "sal", "tier": "dificil", "traps": ["KMnO_3", "K_2MnO_4", "KMn_2O_4"], "why": "Permanganato é MnO₄⁻: KMnO₄, de cor roxa intensa."}
  ],
  physics: [
    {"name": "Velocidade média", "lhs": "v_m", "rhs": "Δs/Δt", "tier": 1, "traps": ["Δt/Δs", "Δs·Δt", "Δs/Δt^2"], "why": "Velocidade média é o deslocamento dividido pelo tempo gasto.", "unit": "m/s", "unit_traps": ["m/s^2", "m", "s"]},
    {"name": "Aceleração média", "lhs": "a_m", "rhs": "Δv/Δt", "tier": 1, "traps": ["Δv·Δt", "Δt/Δv", "Δs/Δt"], "why": "Aceleração é a variação da velocidade dividida pelo tempo.", "unit": "m/s^2", "unit_traps": ["m/s", "N", "m"]},
    {"name": "2ª lei de Newton", "lhs": "F_R", "rhs": "m·a", "tier": 1, "traps": ["m·v", "m/a", "m·a^2"], "why": "Força resultante é massa vezes aceleração (não velocidade).", "unit": "N", "unit_traps": ["kg", "J", "m/s^2"]},
    {"name": "Peso", "lhs": "P", "rhs": "m·g", "tier": 1, "traps": ["m/g", "m·g^2", "m·g/2"], "why": "Peso é a massa vezes a aceleração da gravidade.", "unit": "N", "unit_traps": ["kg", "J", "Pa"]},
    {"name": "Densidade", "lhs": "ρ", "rhs": "m/V", "tier": 1, "traps": ["V/m", "m·V", "m·g/V"], "why": "Densidade é massa dividida pelo volume ocupado.", "unit": "kg/m^3", "unit_traps": ["kg", "kg/m^2", "N/m^3"]},
    {"name": "Pressão", "lhs": "p", "rhs": "F/A", "tier": 1, "traps": ["F·A", "A/F", "F/d"], "why": "Pressão é força dividida pela área em que ela atua.", "unit": "Pa", "unit_traps": ["N", "N·m", "J"]},
    {"name": "Frequência", "lhs": "f", "rhs": "1/T", "tier": 1, "traps": ["1/T^2", "T", "2·π·T"], "why": "Frequência é o inverso do período.", "unit": "Hz", "unit_traps": ["s", "rad", "m/s"]},
    {"name": "Período no MCU", "lhs": "T", "rhs": "2·π/ω", "tier": 1, "traps": ["2·π·ω", "π/ω", "1/ω"], "why": "No MCU o período é uma volta (2π rad) dividida pela velocidade angular ω.", "unit": "s", "unit_traps": ["rad/s", "Hz", "rad"]},
    {"name": "Força de atrito", "lhs": "F_{at}", "rhs": "μ·N", "tier": 1, "traps": ["μ·N^2", "N/μ", "μ/N"], "why": "Atrito é o coeficiente μ vezes a força normal N.", "unit": "N", "unit_traps": ["kg", "J", "adimensional"]},
    {"name": "3ª lei de Newton", "lhs": "F_{AB}", "rhs": "-F_{BA}", "tier": 1, "traps": ["F_{BA}", "2·F_{BA}", "F_{BA}/2"], "why": "Ação e reação têm o mesmo módulo e direção, com sentidos opostos.", "unit": "N", "unit_traps": ["kg", "J", "m/s^2"]},
    {"name": "Função horária do MU", "lhs": "s", "rhs": "s_0 + v·t", "tier": 1, "traps": ["s_0 + v·t^2", "s_0·v·t", "s_0 + v/t"], "why": "No MU a posição cresce linearmente: s = s_0 + v·t.", "unit": "m", "unit_traps": ["m/s", "s", "m/s^2"]},
    {"name": "Conversão km/h → m/s", "lhs": "v_{m/s}", "rhs": "v_{km/h}/3,6", "tier": 1, "traps": ["v_{km/h}·3,6", "v_{km/h}/60", "v_{km/h}/1000"], "why": "De km/h para m/s divide por 3,6; de m/s para km/h multiplica.", "unit": "m/s", "unit_traps": ["km/h", "m", "s"]},
    {"name": "Velocidade angular", "lhs": "ω", "rhs": "Δθ/Δt", "tier": 1, "traps": ["Δt/Δθ", "Δθ·Δt", "Δθ/Δt^2"], "why": "Velocidade angular é o ângulo percorrido dividido pelo tempo.", "unit": "rad/s", "unit_traps": ["m/s", "rad", "rad/s^2"]},
    {"name": "Energia cinética", "lhs": "E_c", "rhs": "m·v^2/2", "tier": 2, "traps": ["m·v/2", "m·v^2", "m^2·v/2"], "why": "Energia cinética tem v ao quadrado e divide por 2.", "unit": "J", "unit_traps": ["N", "W", "kg·m/s"]},
    {"name": "Energia potencial gravitacional", "lhs": "E_p", "rhs": "m·g·h", "tier": 2, "traps": ["m·g/h", "m·g·h/2", "m·g·h^2"], "why": "Energia potencial gravitacional é m·g·h, sem dividir por 2.", "unit": "J", "unit_traps": ["N", "W", "Pa"]},
    {"name": "Trabalho de força constante", "lhs": "τ", "rhs": "F·d·cos θ", "tier": 2, "traps": ["F·d·sen θ", "F/d·cos θ", "F·d·tg θ"], "why": "Trabalho usa o cosseno do ângulo entre força e deslocamento.", "unit": "J", "unit_traps": ["N", "W", "N/m"]},
    {"name": "Potência média", "lhs": "Pot", "rhs": "τ/Δt", "tier": 2, "traps": ["τ·Δt", "Δt/τ", "τ/Δt^2"], "why": "Potência é trabalho (ou energia) dividido pelo tempo.", "unit": "W", "unit_traps": ["J", "N", "J·s"]},
    {"name": "Potência e velocidade", "lhs": "Pot", "rhs": "F·v", "tier": 2, "traps": ["F/v", "F·v^2", "F·v/2"], "why": "Potência de uma força é força vezes velocidade.", "unit": "W", "unit_traps": ["J", "N", "N/s"]},
    {"name": "Quantidade de movimento", "lhs": "Q", "rhs": "m·v", "tier": 2, "traps": ["m·v^2", "m·v/2", "m·a"], "why": "Quantidade de movimento é massa vezes velocidade, sem quadrado.", "unit": "kg·m/s", "unit_traps": ["N", "J", "m/s"]},
    {"name": "Impulso", "lhs": "I", "rhs": "F·Δt", "tier": 2, "traps": ["F/Δt", "F·Δt^2", "F·Δs"], "why": "Impulso é força vezes o intervalo de tempo de atuação.", "unit": "N·s", "unit_traps": ["N", "J", "N/s"]},
    {"name": "Teorema do impulso", "lhs": "I", "rhs": "ΔQ", "tier": 2, "traps": ["ΔE_c", "Q·Δt", "m·a"], "why": "O impulso é igual à variação da quantidade de movimento.", "unit": "N·s", "unit_traps": ["J", "W", "kg·m"]},
    {"name": "Lei de Hooke", "lhs": "F_{el}", "rhs": "k·x", "tier": 2, "traps": ["k·x^2", "k/x", "k·x^2/2"], "why": "Força elástica é proporcional à deformação: F = k·x.", "unit": "N", "unit_traps": ["N/m", "J", "m"]},
    {"name": "Energia potencial elástica", "lhs": "E_{pe}", "rhs": "k·x^2/2", "tier": 2, "traps": ["k·x/2", "k·x^2", "k^2·x/2"], "why": "Energia elástica tem x ao quadrado e divide por 2.", "unit": "J", "unit_traps": ["N", "N/m", "W"]},
    {"name": "Energia mecânica", "lhs": "E_m", "rhs": "E_c + E_p", "tier": 2, "traps": ["E_c - E_p", "E_c·E_p", "E_c/E_p"], "why": "Energia mecânica é a soma da cinética com a potencial.", "unit": "J", "unit_traps": ["N", "W", "kg·m/s"]},
    {"name": "Rendimento", "lhs": "η", "rhs": "Pot_u/Pot_t", "tier": 2, "traps": ["Pot_t/Pot_u", "Pot_u - Pot_t", "Pot_u·Pot_t"], "why": "Rendimento é a potência útil dividida pela total, nunca maior que 1.", "unit": "adimensional", "unit_traps": ["W", "J", "N"]},
    {"name": "Teorema da energia cinética", "lhs": "τ_R", "rhs": "ΔE_c", "tier": 2, "traps": ["ΔE_p", "ΔQ", "E_c·Δt"], "why": "O trabalho da força resultante é igual à variação da energia cinética.", "unit": "J", "unit_traps": ["N", "W", "N·s"]},
    {"name": "Trabalho da força peso", "lhs": "τ_P", "rhs": "m·g·h", "tier": 2, "traps": ["m·g/h", "m·g·h/2", "m·h"], "why": "Trabalho do peso é m·g·h e só depende do desnível h.", "unit": "J", "unit_traps": ["N", "W", "Pa"]},
    {"name": "Energia cinética e momento", "lhs": "E_c", "rhs": "Q^2/(2·m)", "tier": 2, "traps": ["Q^2/m", "Q/(2·m)", "Q^2·m/2"], "why": "Como Q = m·v, E_c = m·v^2/2 vira Q^2/(2·m).", "unit": "J", "unit_traps": ["N·s", "W", "kg·m/s"]},
    {"name": "Equação fundamental da ondulatória", "lhs": "v", "rhs": "λ·f", "tier": 3, "traps": ["λ/f", "f/λ", "λ·T"], "why": "Velocidade da onda é comprimento de onda vezes frequência.", "unit": "m/s", "unit_traps": ["m", "Hz", "m/s^2"]},
    {"name": "1ª lei de Ohm", "lhs": "U", "rhs": "R·i", "tier": 3, "traps": ["R/i", "i/R", "R·i^2"], "why": "Tensão é resistência vezes corrente: U = R·i.", "unit": "V", "unit_traps": ["A", "Ω", "W"]},
    {"name": "Potência elétrica", "lhs": "Pot_{el}", "rhs": "U·i", "tier": 3, "traps": ["U/i", "U·i^2", "U^2·i"], "why": "Potência elétrica é tensão vezes corrente.", "unit": "W", "unit_traps": ["V", "J", "A"]},
    {"name": "Efeito Joule (R·i^2)", "lhs": "P_{el}", "rhs": "R·i^2", "tier": 3, "traps": ["R·i", "R^2·i", "R/i^2"], "why": "Substituindo U = R·i em P = U·i, fica P = R·i^2.", "unit": "W", "unit_traps": ["V", "Ω", "J"]},
    {"name": "Potência elétrica (U^2/R)", "lhs": "P_{el}", "rhs": "U^2/R", "tier": 3, "traps": ["U/R", "R/U^2", "U^2·R"], "why": "Substituindo i = U/R em P = U·i, fica P = U^2/R.", "unit": "W", "unit_traps": ["V", "Ω", "J"]},
    {"name": "Calor sensível", "lhs": "Q", "rhs": "m·c·Δθ", "tier": 3, "traps": ["m·c/Δθ", "m·L", "c·Δθ"], "why": "Calor sensível muda a temperatura: Q = m·c·Δθ.", "unit": "J", "unit_traps": ["W", "J/kg", "J/(kg·°C)"]},
    {"name": "Calor latente", "lhs": "Q", "rhs": "m·L", "tier": 3, "traps": ["m·c·Δθ", "m/L", "L/m"], "why": "Calor latente muda o estado sem mudar a temperatura: Q = m·L.", "unit": "J", "unit_traps": ["W", "J/kg", "K"]},
    {"name": "Força centrípeta", "lhs": "F_{cp}", "rhs": "m·v^2/R", "tier": 3, "traps": ["m·v/R", "m·v^2·R", "m·v^2/(2·R)"], "why": "Força centrípeta tem v ao quadrado dividido pelo raio, sem o 2.", "unit": "N", "unit_traps": ["J", "m/s^2", "kg"]},
    {"name": "Empuxo", "lhs": "E", "rhs": "ρ_f·V_i·g", "tier": 3, "traps": ["ρ_f·V_i/g", "ρ_c·V_i·g", "ρ_f·g"], "why": "Empuxo usa a densidade do fluido e o volume imerso: ρ_f·V_i·g.", "unit": "N", "unit_traps": ["kg", "Pa", "J"]},
    {"name": "Pressão hidrostática", "lhs": "p", "rhs": "ρ·g·h", "tier": 3, "traps": ["ρ·g/h", "ρ·h", "ρ·g·h^2"], "why": "Pressão da coluna de líquido é densidade vezes g vezes profundidade.", "unit": "Pa", "unit_traps": ["N", "kg/m^3", "J"]},
    {"name": "Lei de Stevin", "lhs": "p", "rhs": "p_0 + ρ·g·h", "tier": 3, "traps": ["p_0 - ρ·g·h", "p_0·ρ·g·h", "p_0 + ρ·h"], "why": "Pressão total é a atmosférica mais a da coluna: p_0 + ρ·g·h.", "unit": "Pa", "unit_traps": ["N", "J", "kg/m^3"]},
    {"name": "Período do pêndulo simples", "lhs": "T", "rhs": "2·π·√(L/g)", "tier": 3, "traps": ["2·π·√(g/L)", "2·π·√(L·g)", "2·π·L/g"], "why": "Pêndulo: raiz de L sobre g; não depende da massa.", "unit": "s", "unit_traps": ["Hz", "m", "m/s"]},
    {"name": "Período do sistema massa-mola", "lhs": "T", "rhs": "2·π·√(m/k)", "tier": 3, "traps": ["2·π·√(k/m)", "2·π·m/k", "2·π·√(m·k)"], "why": "Massa-mola: raiz de m sobre k; mola mais dura, período menor.", "unit": "s", "unit_traps": ["Hz", "N/m", "kg"]},
    {"name": "2ª lei de Ohm", "lhs": "R", "rhs": "ρ·L/A", "tier": 3, "traps": ["ρ·A/L", "ρ·L·A", "L/(ρ·A)"], "why": "Resistência cresce com o comprimento e diminui com a área.", "unit": "Ω", "unit_traps": ["V", "A", "Ω·m"]},
    {"name": "Resistores em série", "lhs": "R_{eq}", "rhs": "R_1 + R_2", "tier": 3, "traps": ["R_1·R_2/(R_1+R_2)", "R_1·R_2", "1/R_1 + 1/R_2"], "why": "Em série as resistências simplesmente se somam.", "unit": "Ω", "unit_traps": ["V", "A", "W"]},
    {"name": "Resistores em paralelo", "lhs": "R_{eq}", "rhs": "R_1·R_2/(R_1+R_2)", "tier": 3, "traps": ["R_1 + R_2", "(R_1+R_2)/(R_1·R_2)", "R_1·R_2"], "why": "Paralelo de dois resistores: produto sobre a soma.", "unit": "Ω", "unit_traps": ["V", "A", "W"]},
    {"name": "Carga do capacitor", "lhs": "Q", "rhs": "C·U", "tier": 3, "traps": ["C/U", "U/C", "C·U^2/2"], "why": "Da definição C = Q/U, a carga é Q = C·U (C·U²/2 é a energia).", "unit": "C", "unit_traps": ["F", "V", "A"]},
    {"name": "Equação de Gauss (lentes)", "lhs": "1/f", "rhs": "1/p + 1/p'", "tier": 3, "traps": ["1/p - 1/p'", "p + p'", "p·p'/(p+p')"], "why": "Gauss: os inversos se somam, 1/f = 1/p + 1/p'.", "unit": "1/m", "unit_traps": ["m", "cm", "adimensional"]},
    {"name": "Dilatação linear", "lhs": "ΔL", "rhs": "L_0·α·Δθ", "tier": 3, "traps": ["L_0·α/Δθ", "α·Δθ", "L_0·α·Δθ^2"], "why": "Dilatação depende do tamanho inicial, do material (α) e do Δθ.", "unit": "m", "unit_traps": ["°C", "m/°C", "adimensional"]},
    {"name": "Gravitação universal", "lhs": "F", "rhs": "G·M·m/d^2", "tier": 4, "traps": ["G·M·m/d", "G·M/d^2", "G·M·m·d^2"], "why": "Força gravitacional: produto das massas sobre a distância ao quadrado.", "unit": "N", "unit_traps": ["J", "m/s^2", "kg"]},
    {"name": "Lei de Coulomb", "lhs": "F", "rhs": "k·Q·q/d^2", "tier": 4, "traps": ["k·Q·q/d", "k·Q/d^2", "k·Q·q·d^2"], "why": "Coulomb: produto das cargas sobre a distância ao quadrado.", "unit": "N", "unit_traps": ["C", "V", "N/C"]},
    {"name": "Equação de Torricelli", "lhs": "v^2", "rhs": "v_0^2 + 2·a·Δs", "tier": 4, "traps": ["v_0^2 + a·Δs", "v_0 + 2·a·Δs", "v_0^2 + 2·a·Δs^2"], "why": "Torricelli: v^2 = v_0^2 + 2·a·Δs, sem o tempo.", "unit": "m^2/s^2", "unit_traps": ["m/s", "m/s^2", "m^2/s"]},
    {"name": "MUV – velocidade", "lhs": "v", "rhs": "v_0 + a·t", "tier": 4, "traps": ["v_0 + a·t^2", "v_0 + a·t/2", "v_0·a·t"], "why": "No MUV a velocidade cresce linearmente: v = v_0 + a·t.", "unit": "m/s", "unit_traps": ["m", "m/s^2", "s"]},
    {"name": "MUV – posição", "lhs": "s", "rhs": "s_0 + v_0·t + a·t^2/2", "tier": 4, "traps": ["s_0 + v_0·t + a·t^2", "s_0 + v_0·t + a·t/2", "s_0 + v_0·t^2 + a·t/2"], "why": "Função horária do MUV: o termo da aceleração é a·t^2/2.", "unit": "m", "unit_traps": ["m/s", "s", "m/s^2"]},
    {"name": "Equação de Clapeyron", "lhs": "p·V", "rhs": "n·R·T", "tier": 4, "traps": ["n·R/T", "n·T/R", "n·R·T^2"], "why": "Gás ideal: p·V = n·R·T, com T em kelvin.", "unit": "J", "unit_traps": ["Pa", "K", "mol"]},
    {"name": "1ª lei da termodinâmica", "lhs": "ΔU", "rhs": "Q - τ", "tier": 4, "traps": ["Q + τ", "τ - Q", "Q·τ"], "why": "Energia interna: calor recebido menos trabalho realizado pelo gás.", "unit": "J", "unit_traps": ["K", "W", "Pa"]},
    {"name": "Lei de Snell", "lhs": "n_1·sen θ_1", "rhs": "n_2·sen θ_2", "tier": 4, "traps": ["n_2·cos θ_2", "n_2/sen θ_2", "n_1·sen θ_2"], "why": "Snell: n·sen θ é o mesmo nos dois meios.", "unit": "adimensional", "unit_traps": ["rad", "m/s", "m"]},
    {"name": "Energia do fóton", "lhs": "E", "rhs": "h·f", "tier": 4, "traps": ["h/f", "h·λ", "h·f^2"], "why": "Energia do fóton é a constante de Planck vezes a frequência.", "unit": "J", "unit_traps": ["W", "Hz", "J·s"]},
    {"name": "Equivalência massa-energia", "lhs": "E", "rhs": "m·c^2", "tier": 4, "traps": ["m·c", "m·c^2/2", "m^2·c"], "why": "Einstein: E = m·c^2, com c ao quadrado e sem dividir por 2.", "unit": "J", "unit_traps": ["kg", "W", "N"]},
    {"name": "Campo elétrico", "lhs": "E", "rhs": "F/q", "tier": 4, "traps": ["F·q", "q/F", "F/q^2"], "why": "Campo elétrico é força por unidade de carga de prova.", "unit": "N/C", "unit_traps": ["N", "C", "V"]},
    {"name": "Campo de carga puntiforme", "lhs": "E", "rhs": "k·Q/d^2", "tier": 4, "traps": ["k·Q/d", "k·Q·q/d^2", "k·Q^2/d^2"], "why": "Campo de uma carga: k·Q/d^2; com q vira força, com d vira potencial.", "unit": "N/C", "unit_traps": ["N", "V", "C"]},
    {"name": "Alcance do lançamento oblíquo", "lhs": "A", "rhs": "v_0^2·sen(2θ)/g", "tier": 4, "traps": ["v_0^2·sen θ/g", "v_0·sen(2θ)/g", "v_0^2·cos(2θ)/g"], "why": "Alcance usa sen(2θ): máximo em 45°.", "unit": "m", "unit_traps": ["m/s", "s", "m/s^2"]},
    {"name": "Velocidade orbital", "lhs": "v", "rhs": "√(G·M/r)", "tier": 4, "traps": ["√(G·M/r^2)", "G·M/r", "√(G·M·r)"], "why": "Igualando gravidade e centrípeta: v = √(G·M/r).", "unit": "m/s", "unit_traps": ["m/s^2", "m", "N"]},
    {"name": "Rendimento de Carnot", "lhs": "η", "rhs": "1 - T_F/T_Q", "tier": 4, "traps": ["1 - T_Q/T_F", "T_F/T_Q", "1 + T_F/T_Q"], "why": "Carnot: 1 menos a razão fria/quente (T_F/T_Q), em kelvin.", "unit": "adimensional", "unit_traps": ["K", "J", "W"]},
    {"name": "Potencial de carga puntiforme", "lhs": "V", "rhs": "k·Q/d", "tier": 4, "traps": ["k·Q/d^2", "k·Q·d", "k·Q^2/d"], "why": "Potencial cai com d (sem quadrado); o campo cai com d^2.", "unit": "V", "unit_traps": ["N/C", "J", "C"]}
  ],
  };
})();
